### ISSUE TITLE
Lovelace configure UI doesn't retain ressources since 0.85.0

### ISSUE THREAD

**Issue by grea09** [home-assistant/home-assistant-polymer#2448] opened 2019-01-11 16:36 UTC
**Home Assistant release with the issue:**
0.85.0

**Last working Home Assistant release (if known):**
0.84.6

**Browser and Operating System:**
Chrome, Ubuntu (installed via pip)

**Description of problem:**
When using the configure UI, ressources arren't retained even when added in the raw editor. Custom cards fail to load properly becuase of it.

**Additional information:**
This seems to work still on an old Android tablet (probably cache)

**Comment by iantrich** [comment] 2019-01-11 17:41
duplicate of https://github.com/home-assistant/home-assistant-polymer/issues/2436

**Closed by iantrich** 2019-01-11 17:41 UTC
