### ISSUE TITLE
Display issues on the History menu in Safari and in the iOS app

### ISSUE THREAD

**Issue by Lato80** [home-assistant/home-assistant-polymer#712] opened 2017-12-05 09:08 UTC
The data in the History menu is not displayed in Safari (macOS & iOS) and not in the iOS app.

It does not matter what attitude I use:

```
frontend:
  javascript_version: latest | auto | es5
```

But does not seem to be a fundamental problem, because in Mozilla Firefox or Google Chrome, the data is displayed to me.

**Comment by andrey-git** [comment] 2017-12-05 10:03
Which version of Safari is it?
Any JS errors in Safari dev tools console?

Also to make sure to do a hard refresh after switching between js versions.

**Comment by Lato80** [comment] 2017-12-05 10:25
The current Safari versions: 11.0.1 on macOS and iOS 11.2 included.

In the Developer Console, I get the following errors / warnings after a hard refresh:

<img width="1489" alt="bildschirmfoto 2017-12-05 um 11 15 47" src="https://user-images.githubusercontent.com/33683662/33602025-5ab3f92c-d9ae-11e7-890a-439fa90bcb34.png">

I also made a hard refresh after each change of the JS version.

I've just seen the graphs flashing during the updates to the developer console messages. Maybe this info will help you.

**Comment by balloob** [comment] 2017-12-06 06:51
Can you show a screenshot of the date not showing. Exactly which history menu are you talking about?

**Comment by Lato80** [comment] 2017-12-06 08:55
That's how it looked all the time and I could wait for minutes, nothing happened:

Safari 11.0.1 on macOS:
![bildschirmfoto 2017-12-06 um 09 44 09](https://user-images.githubusercontent.com/33683662/33652680-9350ebb6-da6a-11e7-8646-deb40ffa9677.png)

HASS-App on iOS 11:
![img_0064](https://user-images.githubusercontent.com/33683662/33652731-c048ad5c-da6a-11e7-8020-17236ebde938.png)

I have not done or changed anything on the system since yesterday. I just wanted to take the screen shots and lo and behold, the graphics are displayed.

But why is it working in the Safari / iOS app now? Before I could only look at the graphics in Firefox or Chrome, but not in Safari. I'm a bit confused and can not explain it yet. I do not know if the problem occurs again, what can I do there.

**Comment by balloob** [comment] 2017-12-07 03:34
From the Safari JS console

![image](https://user-images.githubusercontent.com/1444314/33697568-791e4b7e-dabc-11e7-9429-bd7bc81a2490.png)

**Comment by andrey-git** [comment] 2017-12-07 05:21
Ill take a look later.
Can you also reproduce this in Dev mode?

**Comment by Lato80** [comment] 2017-12-07 15:59
Today it does not work in Safari again. In Firefox, everything continues to run wonderfully.

**Comment by jmesberg** [comment] 2018-01-06 14:22
I have exactly the same issue. No point in adding any further detail since it is literally identical

**Comment by balloob** [comment] 2018-01-07 07:07
This has been fixed in 0.60.1 by https://github.com/home-assistant/home-assistant/pull/11387

**Closed by balloob** 2018-01-07 07:07 UTC
