### ISSUE TITLE
Hide the edit button on the map panel from non-administrators

### ISSUE THREAD

**Issue by sgttrs** [home-assistant/home-assistant-polymer#4790] opened 2020-02-06 11:22 UTC
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

At the moment, the user sees the edit button on the map panel, clicking on it opens a blank screen.

## Expected behavior

Hide the button from users, as they do not have edit rights.

## Steps to reproduce

    1. Login as a user
    2. Open Map panel
    3. Click Edit button

## Environment

- Home Assistant release with the issue: 0.105.1
- Last working Home Assistant release (if known): n/a
- UI Type (States or Lovelace): Lovelace
- Browser and browser version: Chrome
- Operating system: Windows

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by bramkragten** [comment] 2020-02-10 11:05
duplicate of https://github.com/home-assistant/home-assistant-polymer/issues/4737

**Closed by bramkragten** 2020-02-10 11:05 UTC
Labels: bug
