### ISSUE TITLE
Feature request: Create new Zone based on phone's current GPS location

### ISSUE THREAD

**Issue by donkawechico** [home-assistant/home-assistant-polymer#4827] opened 2020-02-10 19:15 UTC
Now that HA Core has the awesome new [Zone editor](https://www.home-assistant.io/blog/2020/02/05/release-105/#improved-zones-editor), it would be handy to be able to create a named zone based on my current GPS location.

The current process (look up address, grab it's lat/long, paste into zone editor) is still fiddly, and doesn't account for situations where the address isn't sufficient. For example, a certain area along your subway commute that you can only really identify when you're physically there.

**Comment by bramkragten** [comment] 2020-02-10 19:30
duplicate of https://github.com/home-assistant/home-assistant-polymer/issues/4561

**Closed by bramkragten** 2020-02-10 19:30 UTC
