### ISSUE TITLE
Forecast dates/times in weather card incorrect in some browsers

### ISSUE THREAD

**Issue by brlodi** [home-assistant/home-assistant-polymer#2506] opened 2019-01-20 03:43 UTC
**Home Assistant release with the issue:**
0.85.1

**Last working Home Assistant release (if known):**
N/A

**Browser and Operating System:**
Inconsistency across browsers is the issue, but a minimal pair is Safari (or the iOS app which uses the same rendering backend) and Chrome/Chromium.

**Description of problem:**
As discussed in home-assistant/home-assistant#16548, on some browsers the forecast date/times in the weather card are displayed as doubly-offset from UTC, i.e. users in UTC-5 timezones see 5PM instead of 10PM while users in UTC-6 would see 4PM.

**Javascript errors shown in the web inspector (if applicable):**
```

```

**Additional information:**
Having determined that behavior varies between browsers, and having worked with JavaScript's implementation-depended date time handling, I suspected `Date.parse()` was being used somewhere. The culprit seems to be [these one-off date formatting functions in `ha-weather-card.js`](https://github.com/home-assistant/home-assistant-polymer/blob/233b646917a41f771e8e96991344fc941badb43c/src/cards/ha-weather-card.js#L367). Replacing them with proper calls to whatever home-assistant-polymer's standard date formatting functions are, which I believe pipe through the fecha library, will probably resolve the issue.

**Comment by scottyphillips** [comment] 2019-01-26 07:57
@brlodi do you know issue been fixed in 0.86 or something? The stock Dark sky weather component seems to be working correctly again now in Safari..... Could possibly be that the default UI is now lovelace in 0.86?

**Comment by iantrich** [comment] 2019-02-14 03:27
duplicate of https://github.com/home-assistant/home-assistant-polymer/issues/2249

@brlodi how do you feel about submitting a PR with a fix?

**Closed by iantrich** 2019-02-14 03:27 UTC
Labels: element: weather

**Comment by brlodi** [comment] 2019-03-01 23:59
@iantrich sorry this got lost in the deluge of GitHub notifications from work. I can probably take a look at it this weekend and submit a PR

**Comment by WilkyF18** [comment] 2019-03-11 03:18
Has then been fixed?

**Comment by KageKeeper** [comment] 2019-03-19 04:42
Still seeing this issue in 0.89.1

**Comment by iantrich** [comment] 2019-03-19 04:57
This issue is closed for #2249 which is where any updates/questions should be made

**Comment by piersdd** [comment] 2019-05-05 04:04
Still seeing this issue in 0.92.2
