### ISSUE TITLE
Wrong Media player component icon color

### ISSUE THREAD

**Issue by redstar2k1** [home-assistant/home-assistant-polymer#3410] opened 2019-07-22 06:18 UTC
**Home Assistant release with the issue:**
0.95.4

**Last working Home Assistant release (if known):**

**UI (States or Lovelace UI?):**
Lovelace

**Browser and Operating System:**
Chrome & Firefox, Ubuntu 18.0.4 LTS

**Description of problem:**
Media players icons not showing the right “active/on” color. They are shown in the “inactive/default/off” color no mater if they are on/idle/playing.

**Javascript errors shown in the web inspector (if applicable):**
```

```

**Additional information:**
![AwesomeScreenshot-Home-Assistant-2019-07-18-14-07-98](https://user-images.githubusercontent.com/26925758/61610325-81bd9000-ac61-11e9-9223-5a028e833a96.png)
![AwesomeScreenshot-Home-Assistant-2019-07-18-14-07-80](https://user-images.githubusercontent.com/26925758/61610326-81bd9000-ac61-11e9-8d3d-5cd1de501db0.png)

**Comment by iantrich** [comment] 2019-08-31 14:45
Duplicate of https://github.com/home-assistant/ui-schema/issues/178

**Closed by iantrich** 2019-08-31 14:45 UTC
