### ISSUE TITLE
input_number in box mode shown truncated when UI has more than 1 column

### ISSUE THREAD

**Issue by sagilo** [home-assistant/home-assistant-polymer#778] opened 2018-01-03 09:27 UTC
Here is the configuration : 

    input_number:
      switcher_operation_time:
        name: Time
        icon: mdi:clock
        mode: box
        initial: 30
        min: 5
        max: 90
        step: 5

Here is how it looks when UI has 2 columns : 
<img width="399" alt="screenshot 2018-01-02 15 13 14" src="https://user-images.githubusercontent.com/5019344/34484785-da8a2f7c-efcf-11e7-817e-67681b69c8a8.png">

That's with 3 columns:
<img width="341" alt="screenshot 2018-01-02 15 12 56" src="https://user-images.githubusercontent.com/5019344/34484791-e5555a76-efcf-11e7-9a69-3c900bc06a3f.png">

**Comment by Shawndrea** [comment] 2018-01-03 14:52
input_number:
  switcher_operation_time:
    name: Time
    icon: mdi:clock
    mode: box
    initial: 30
    min: 5
    max: 90
    step: 5

**Comment by c727** [comment] 2018-04-04 16:19
Can't reproduce. Please provide more information: HA version, browser, ...

**Comment by NovapaX** [comment] 2018-04-04 17:45
I think this is not relevant anymore. see #802 and #808.
Closing. Please file a new issue if there are still problems with this.

**Closed by NovapaX** 2018-04-04 17:45 UTC
Labels: User feedback required
