### ISSUE TITLE
Errors in thermostats temperature graph

### ISSUE THREAD

**Issue by bieniu** [home-assistant/home-assistant-polymer#240] opened 2017-03-19 21:17 UTC
HA 0.40.x (0.39.x also) shows errors in termostats temperature graphs. My thermostats are Danfoss 014G0013.
![graphs](https://cloud.githubusercontent.com/assets/478555/24084813/8fbff3a8-0cf1-11e7-8fc6-3720cc3e2999.png)

**Comment by bieniu** [comment] 2017-03-22 05:38
My today thermostat graph.
![screenshot_20170322-063237](https://cloud.githubusercontent.com/assets/478555/24183651/080c2276-0eca-11e7-94e6-7483c5bb22a0.png)

**Comment by jannau** [comment] 2017-03-23 17:52
That is not limited to the danfoss thermostats. I see something similar with my homematic thermostats. It looks like the most recent value is around time of the last start of home-assistant. The associated temperature sensors of the homematic thermostats do not show this. The eq3btsmart thermostat in another home-assistant installation works as expected.

**Comment by n0dyjeff** [comment] 2017-03-23 19:31
I see this also with two Ecobee thermostats. Looks like a line is being drawn between the current time/temp and the same temp at the time of restart. Doesn't appear to be happening in the History window, only the climate card.
![image](https://cloud.githubusercontent.com/assets/24596414/24266537/521baaa8-0fc4-11e7-8fd0-6cc817b06c56.png)

**Comment by bieniu** [comment] 2017-03-26 09:09
Unfortunately, the issue has not been fixed in the 0.41 release.

**Comment by jannau** [comment] 2017-04-05 20:00
The problem is that the state of the climate component (for the homematic thermostats the operation mode) changes rarely to never. So last_changed keeps constant and the climate graph seems to draw a line from the last last_update time to the last_changed time. Might be fixed by #254

**Comment by jannau** [comment] 2017-04-05 20:36
yes, should be fixed by #254

**Comment by n0dyjeff** [comment] 2017-04-09 17:56
Yep, it's fixed! Just tried in 0.42. Great job, and thanks!

**Comment by bieniu** [comment] 2017-04-09 18:52
Yes, it's fixed! Great!

**Closed** 2017-04-14 15:19 UTC
