### ISSUE TITLE
GUI Editor in Lovelace Disabled in Panel mode

### ISSUE THREAD

**Issue by DavidFW1960** [home-assistant/home-assistant-polymer#3416] opened 2019-07-24 02:15 UTC
0.96.3
**Home Assistant release with the issue:**

**Last working Home Assistant release (if known):**
unknown
**UI (States or Lovelace UI?):**
Lovelace

**Browser and Operating System:**

Chrome on Windows 10
**Description of problem:**

**Javascript errors shown in the web inspector (if applicable):**
```

```

**Additional information:**

**Comment by tomlut** [comment] 2019-07-24 02:26
Just to be clear, it's not 'disabled' as such, you can enter the config UI mode when in a panel view. It's just that the edit options below cards in the panel view are missing.

**Comment by iantrich** [comment] 2019-07-24 02:28
Duplicate of #2625

**Closed by iantrich** 2019-07-24 02:28 UTC
