### ISSUE TITLE
Disable editing scripts that were created by hand, allow hiding automations and scripts from the UI editor

### ISSUE THREAD

**Issue by Misiu** [home-assistant/home-assistant-polymer#4839] opened 2020-02-11 09:09 UTC
## The request

Currently, automations created by hand (in YAML) that don't have a unique id specified. are shown as non-editable in `config/automation` (the pencil is gray and disabled)
Unfortunately, the same behavior isn't applied to scripts.
When you navigate to `config/script` you see a list of all scripts, you can edit them and, the worst part, delete them!

Both places should have the same, consistent behavior- if automation or script doesn't have an id it shouldn't be editable via UI.

## Additional information
Ideally, we should be able to hide some of the automations and scripts from those lists.
I have a couple of automations that run in the background and I'd like to avoid someone turning them off, same with scripts, I don't want someone to run them manually or delete them.
How about a `hidden` property for both? This would allow backward compatibility (default false) but would allow us to hide certain elements from those lists

**Comment by bramkragten** [comment] 2020-02-11 09:40
duplicate of https://github.com/home-assistant/home-assistant-polymer/issues/3563

**Closed by bramkragten** 2020-02-11 09:40 UTC
Labels: feature request

**Comment by Misiu** [comment] 2020-02-11 10:51
@bramkragten I didn't fount that one. Thanks!
What about the ability to hide scripts and automation from UI editor? Should I create a separate feature request for that?

**Comment by bramkragten** [comment] 2020-02-11 11:27
I believe hidden is deprecated <https://github.com/home-assistant/home-assistant/pull/30799>, so we will not implement that. I seems you are looking for some authorization options more than a hide option?

**Comment by Misiu** [comment] 2020-02-11 11:36
@bramkragten I have an admin account, this allows me to edit everything, but I can't give admin to everyone. I'd like to have the ability to allow a specific user to create automations and edit his automations. If I give him admin access he will be able to change/edit everything. My idea was to hide automations and scripts I describe as "required for the system to work".

A simple use case:
I'd like to be able to give the user the ability to create an automation that will turn the light on or off or set specific temperature on the thermostat.
I'm aware I can do everything via UI (add items to lovelance that will allow him to specify conditions), but I really like the Automation Editor and I'd like to give access to it for some more advanced users, but with ability to hide some actions they shouldn't see.

So yes, this is more a permission issue (feature request), but hiding was the easiest way to accomplish that.
