### ISSUE TITLE
GUI does not load in Tesla web browser

### ISSUE THREAD

**Issue by freerobby** [home-assistant/home-assistant-polymer#133] opened 2016-10-20 23:36 UTC
When browsing a HA server from the Tesla browser, the request comes through to the server but it never gets to authentication or into the app itself. Server logs show a request coming through, but nothing more and no errors. I wish I could give more useful information, but Tesla does not have any client-side tools for debugging. I wrote them asking if they have a spec of what is and is not supported; they don't.

I figured I'd log this issue, unhelpful as it is, and if I can deduce any more info I will add it here.

**Comment by balloob** [comment] 2016-10-20 23:41
Does it show the logo and login form? 

It's probably related to the tesla browser being outdated and not supporting promises. What engine is it based on?

**Comment by freerobby** [comment] 2016-10-21 00:26
I see the logo, but not the login form. Text reads "Home Assistant had trouble".

I see one entry in the server log:

> 16-10-20 20:21:55 INFO (CP Server Thread-18) [homeassistant.components.http] Serving / to 173.76.179.38 (auth: False)

Browser is webkit-based, but clearly modified (e.g. it blocks video assets). Agent is:

> Mozilla/5.0 (X11; Linux) AppleWebKit/534.34 (KHTML, like Gecko) QtCarBrowser Safari/534.34

**Comment by justweb1** [comment] 2016-10-25 12:24
Since the trouble is caused by your not standardized browser I'm marking this as a won't fix for now unless @balloob decides otherwise.

**Comment by fabaff** [comment] 2016-10-25 12:29
Not everybody is happy with that broswer...https://forums.tesla.com/forum/forums/tesla-web-browser

**Closed** 2016-11-12 12:33 UTC
Labels: wontfix
