### ISSUE TITLE
Component styles get lost during navigation

### ISSUE THREAD

**Issue by sehaas** [home-assistant/home-assistant-polymer#2763] opened 2019-02-16 11:29 UTC
**Home Assistant release with the issue:**
0.87.1 (Docker)

**Last working Home Assistant release (if known):**

**Browser and Operating System:**
- Chrome Version 73.0.3683.39 (Official Build) beta (64-bit) / OSX
- Chrome Dev 74.0.3702.2 / Android 9

**Description of problem:**
1. Open Overview => badges are rendered with correct style
![ha_overview_css](https://user-images.githubusercontent.com/283482/52898964-a1e5b080-31e4-11e9-9450-92f9117eb7aa.png)
2. Navigate to any other page (eg. Map, Logbook, History)
3. Navigate back to Overview => badges are not rendered correctly
![ha_overview_nocss](https://user-images.githubusercontent.com/283482/52898971-b7f37100-31e4-11e9-80f5-7dd2fbe07e11.png)
4. Reload page => badges are rendered with correct style

**Additional information:**
Problem does not exist with Firefox 65.0.1
Maybe it is a general problem with the upcoming Chrome builds, but I haven't found any information or experienced the problem on anywhere else so far.

**Comment by iantrich** [comment] 2019-02-18 05:28
I am able to replicate on Windows 10, Chrome 74.0.3709.0 (Official Build) canary (64-bit). 

It get's worse though; the first column gets a scrollbar and mwc-buttons are not styled. I think a bug should be reported to Chrome team

![image](https://user-images.githubusercontent.com/1287159/52929874-c8523b80-330b-11e9-901f-6dda84e46443.png)

**Comment by Sirs0ri** [comment] 2019-02-20 22:53
I'm also experiencing this issue on Chrome (Version 73.0.3683.46 (OfficialBuild) beta (64-Bit))/Win10.

When navigating to any /lovelace page that I've visited before all styles seem to be lost, a reload fixes the issue temporarily. Please let me know if there's a way to help track this down (by providing logs, etc)!

**Comment by nkaminski** [comment] 2019-02-21 00:10
Able to reproduce as well on HA 0.87.1 being accessed by Chrome 73.0.3683.39 (Official Build) beta (64-bit) running on Mac OSX 10.14.

**Comment by NearlCrews** [comment] 2019-02-22 17:41
Exact same problem here on HA 0.88.0 with Chrome 73.0.3683.46 (Official Build) beta (64-bit) on Windows 10. I first noticed it on the HA 0.87.1 release. 

It seems to start when I click on a tab made up of history cards:
![1](https://user-images.githubusercontent.com/23341701/53260300-1dd97000-369f-11e9-9474-6ece7ed078fc.png)

...and then formatting is lost until I refresh the page.
![2](https://user-images.githubusercontent.com/23341701/53260322-3053a980-369f-11e9-8b4d-0da91fac8a94.png)

**Comment by NearlCrews** [comment] 2019-02-22 17:46
To add to that, there's another one where the blue bar at the top seems to disappear after clicking on the logbook, although I can't reliably reproduce it.

![3](https://user-images.githubusercontent.com/23341701/53260593-e0c1ad80-369f-11e9-8d2e-f8ef81019d1a.png)

**Comment by sehaas** [comment] 2019-02-23 09:37
Can anyone provide a minimalistic example page for an upstream bug report?

**Comment by balloob** [comment] 2019-02-25 20:32
I am able to repro on Chrome on Android, not on Chrome on my Mac. 

Able to replicate using the demo.

 - Go to https://demo.home-assistant.io/#/lovelace/0
 - Click on the 2nd tab (the `(i)` icon)
 - Click no the 1st tab (the home icon)
 - Notice the first card missing all styling.

**Comment by balloob** [comment] 2019-02-25 20:39
Did some quick debugging on my phone. I think that it's a bug in Chrome.

On a fresh reload of the page, inspecting the first card `<ha-demo-card>`. There is no CSS inside the ShadowDOM, most likely because Lit-Element uses Constructible Stylesheets when possible.

![image](https://user-images.githubusercontent.com/1444314/53367017-e6b2cb00-38f9-11e9-8948-b05bec650368.png)

If we look at one of the styled elements, the source of the styles is attributed to the user agent:

![image](https://user-images.githubusercontent.com/1444314/53367057-03e79980-38fa-11e9-9746-3a0c51c483d3.png)

The actual source of the style is actually a constructible stylesheet: https://github.com/home-assistant/home-assistant-polymer/blob/dev/demo/src/custom-cards/ha-demo-card.ts#L121-L137

After a page change, the CSS of `.picker` is:

![image](https://user-images.githubusercontent.com/1444314/53367129-3b564600-38fa-11e9-8c36-51f3177d6e37.png)

Now, to understand what triggers the bug, it's the removing and appending of a child to the DOM, which happens here: https://github.com/home-assistant/home-assistant-polymer/blob/dev/src/panels/lovelace/hui-root.ts#L603-L648

**Comment by balloob** [comment] 2019-02-25 20:47
Minimal repro here: https://65s7tj-jqi1d9.stackblitz.io
Code at https://stackblitz.com/edit/65s7tj-jqi1d9

**Comment by balloob** [comment] 2019-02-25 20:55
Asked on the Lit Slack, known problem and tracked here: https://github.com/Polymer/lit-element/issues/581

**Comment by balloob** [comment] 2019-02-26 21:06
This will be fixed in Chrome 73.

**Closed by balloob** 2019-02-26 21:06 UTC
Labels: upstream issue

**Comment by Sirs0ri** [comment] 2019-02-28 16:23
Thanks for looking into this!
I'm currently on Chrome Version 73.0.3683.56 beta (64-Bit) and the bug is gone, looks like I already got the fix mentioned in the Polymer-issue linked above.
