### ISSUE TITLE
logbook, history and config tabs are blank on Firefox

### ISSUE THREAD

**Issue by RyuzakiKK** [home-assistant/home-assistant-polymer#840] opened 2018-01-27 13:16 UTC
**Home Assistant release (`hass --version`):**
0.62.0

**Python release (`python3 --version`):**
3.5.2

**Description of problem:**
I'm unable to load the logbook, history and config tabs.

**Additional info:** In the web console I got this error:
```
TypeError: NetworkError when attempting to fetch resource.

resource.ta:function%20getActiveTranslation()%7Bfunction%20n(n)%7Bconst%20a%3Dn.toLowerCase()%3Breturn%20t%:1:987
```

This is how I see the config dashboard
![screenshot from 2018-01-27 13-14-45](https://user-images.githubusercontent.com/3227973/35471918-53b4e9e8-0365-11e8-9cd3-1263f8e92388.png)

I have this error with Firefox 58 stable and with the latest nightly.
Instead Chromium is able to correctly load it.

**Comment by c727** [comment] 2018-01-27 14:21
CTRL+F5, clear cache?

**Comment by RyuzakiKK** [comment] 2018-01-27 14:27
@c727 nope, it doesn't help.

**Comment by andrey-git** [comment] 2018-01-27 18:23
Tried:
* FF 52 (Linux) and with head dev version.
* FF 57 Android

Both work fine

**Comment by balloob** [comment] 2018-01-27 19:50
@RyuzakiKK using the LastPass extension?

**Comment by RyuzakiKK** [comment] 2018-01-27 20:06
@balloob no, I even tried firefox in safe mode with the same result.

I also tried Windows, and there firefox 58 (stable) works and only the nightly doesn't.
The strange thing is that on my linux machine also firefox 58 present this issue.

**Comment by andrey-git** [comment] 2018-01-27 20:09
FF 58 on Linux-64bit (dev at head) works fine for me.

**Comment by RyuzakiKK** [comment] 2018-01-27 20:30
I tried a clean ubuntu vm just to leave all my firefox configurations out of the equation.
- Firefox 58 works
- Firefox 60 nightly doesn't

So just on my machine FF 58 doesn't work (maybe it doesn't some edited configurations, I don't know).

Just a note, on windows and on ubuntu with FF nightly I got a never ending loading if I refreshed the `/config/dashboard` page. But if I simply navigated to it from the `/states` page it worked (insted of the blank screenshot as I posted).

Should this be marked as a FF nightly bug instead of an HA one? In this case feel free to close this issue.

I'll post an update if I'll figure out why on my machine this issue shows up also on FF 58.

**Comment by RyuzakiKK** [comment] 2018-01-27 22:03
Finally I found out the configuration culprit on my FF 58.
It is `network.http.referer.XOriginPolicy` set at 1. This is the explanation of what this means https://wiki.mozilla.org/Security/Referrer

I'm a bit surprised that the ui requires a cross origin referrer in order to correctly work.

**Comment by balloob** [comment] 2018-01-29 08:27
The only cross-origin things that are fetched are the Google Chart scripts. However, those are not loaded on the config.

Maybe there is some race condition when navigating directly to the config page. Weird.

**Comment by NovapaX** [comment] 2018-04-04 19:25
I have just tried to reproduce this in firefox 59, by setting that config parameter, but have not been able to.
I can also not reproduce this never-ending loading of `config/dashboard`
Can anyone check if this is still an issue?

**Comment by RyuzakiKK** [comment] 2018-04-05 16:16
I just tried it again and I'm still able to reproduce this bug.
With `network.http.referer.XOriginPolicy` set at 1  in `about:config` breaks `config/dashboard`, and also part of the lateral menu.
![screenshot from 2018-04-05 18-13-56](https://user-images.githubusercontent.com/3227973/38378224-47488a48-38fd-11e8-9e53-d954f2e272a3.png)

**Comment by NovapaX** [comment] 2018-04-17 14:37
Still can not reproduce this.
The only thing I can think of that could cause this is some problem with sending over the credentials in combination with that setting.
https://github.com/home-assistant/home-assistant-polymer/blob/master/src/util/hass-translation.html#L84

**Comment by RyuzakiKK** [comment] 2018-04-17 20:06
That's really strange.
I tried in a Windows VM with a default installation of Firefox (and no addons) and only setting to 1 the XOriginPolicy is enough to show the bug.
Then I tried with a fresh installation of HA, this time in my local machine (to rule out every possible connection related problem) and once again I'm able to reproduce it.
And I left the default HA configuration, so with no authentication required.

**Comment by NovapaX** [comment] 2018-04-17 21:46
Oh, let me try it in a windows VM too then....

**Comment by NovapaX** [comment] 2018-04-18 10:59
Ok, I've been able to reproduce this. A couple of findings:
- this is related to Firefox its `fetch()` implementation in combination with `network.http.referer.XOriginPolicy` setting on `1`
- It will not even try to `fetch()` the language resources when connecting to the hass instance via: `localhost:8123`, `127.0.0.1:8123` or my local IP-address e.g. `10.199.x.x:8123`
- it did correctly fetch the resources when connecting locally via `my-machine-name.local:8123`

So it looks like `network.http.referer.XOriginPolicy=1` is incompatible with `fetch()`ing resources via IP-address.

**Comment by balloob** [comment] 2018-04-18 14:11
Okay, in that case it's not an issue that we can fix then. We should close this issue?

**Comment by NovapaX** [comment] 2018-04-18 14:17
Yes, I see no easy way to fix this. If you really need/want this option set to `1`, I suggest filing an issue with Mozilla to get some more background on why this is happening. Maybe then we can look at a way to fix it.

**Closed by NovapaX** 2018-04-18 14:17 UTC
