### ISSUE TITLE
Card editor change the input text

### ISSUE THREAD

**Issue by zipposi** [home-assistant/home-assistant-polymer#3481] opened 2019-08-12 05:43 UTC
**Home Assistant release with the issue:** 0.97

**Last working Home Assistant release (if known):** Lovelace UI

**UI (States or Lovelace UI?):**

**Browser and Operating System:** Windows 10, Chrome  75.0.3770.142

**Description of problem:**

The YAML editor for a entity button changes the YAML fter saving. I write this text in the editor

```type: entity-button
tap_action:
  action: call-service
  service: mqtt.publish
  service_data:
    retain: 0
    payload: '<?xml version=\"1.0\" encoding=\"UTF-8\"?><msg><sender>hass-argo</sender><target></target><command>RFID_OPENDOOR</command><params>ReaderId=4</params></msg>'
    topic: topic/subtopic
    qos: 0
hold_action:
  action: none
show_icon: true
show_name: true
entity: climate.soba_3
name: Vhod
icon: 'mdi:door'
```

![HassEditor](https://user-images.githubusercontent.com/42633929/62847229-7cd68400-bcd5-11e9-9bef-0a21612cab5c.PNG)

During the edit I see the button preview and the editor does not show any errors. After clicking "Save", and reopening the editor I get this text.

```type: entity-button
tap_action:
  action: call-service
  service: ''
hold_action:
  action: none
show_icon: true
show_name: true
entity: climate.soba_3
name: Vhod
icon: 'mdi:door'
```

![HassEditor2](https://user-images.githubusercontent.com/42633929/62847295-c0c98900-bcd5-11e9-95d9-c232d1cb64f1.PNG)

Checked the log, no errors at all. 

**Javascript errors shown in the web inspector (if applicable):**
```
No javascript errors in the console
```

**Additional information:**
MQTT integration is active.
Tried different approaches to define the payload (escaped/single/double quotes, empty payload,.. etc.), but no success.
Tried to seolve via support forum (no luck): https://community.home-assistant.io/t/button-to-sen-mqtt-message/130872/2

**Comment by iantrich** [comment] 2019-09-04 00:18
duplicate of https://github.com/home-assistant/home-assistant-polymer/issues/2645

**Closed by iantrich** 2019-09-04 00:18 UTC
