### ISSUE TITLE
iOS app signin does not use password manager

### ISSUE THREAD

**Issue by mkjones** [home-assistant/home-assistant-polymer#4408] opened 2020-01-01 16:23 UTC
**Checklist:**

- [x ] I updated to the latest version available
- [ n/a] I cleared the cache of my browser

**Home Assistant release with the issue:**

0.103.5
**Last working Home Assistant release (if known):**
Not sure if it worked fine fire 
**UI (States or Lovelace UI?):**

Lovelace. Frontend version: 20191204.1 - latest
**Browser and Operating System:**
iOS 13.2. safari. 

**Description of problem:**

When going to the web UI directly in safari or when signing in via the iOS app, the login page presents a username and password entry field.  In my case, this is stored in LastPass or Apple Keychain, and I want to auto fill it from there. 
![30733025-E76B-488A-B0A9-453604600A2D](https://user-images.githubusercontent.com/215337/71643499-712d2f00-2c6f-11ea-9156-d5cd5ddbdc63.png)

**Expected behaviour:**
When I select a username or password field, the gray bar between the webpage and the keyboard suggests I can use a keychain login. 

Actual behavior: nothing happens and I’m not presented with any such option. 

**Relevant config:**
Default hassio install. 

**Steps to reproduce this problem:**
1. Set up bare bones hass.io
2. Point your iPhone app or browser at its address.  
3. Try to log in. 

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by iantrich** [comment] 2020-01-02 15:20
duplicate of https://github.com/home-assistant/home-assistant-polymer/issues/1622

**Closed by iantrich** 2020-01-02 15:20 UTC
Labels: bug
