### ISSUE TITLE
Lovelace UI - showing hidden entities

### ISSUE THREAD

**Issue by austwhite** [home-assistant/home-assistant-polymer#2655] opened 2019-02-02 09:08 UTC
**Home Assistant release with the issue:**

0.86.x
**Last working Home Assistant release (if known):**
had not previously used Lovelace UI

**Browser and Operating System:**

Google Chrome (latest version) Microsoft Edge (all latest updates)
**Description of problem:**

I have several hidden entities, using both customize.yaml and hiding the Z-Wave entity using the z-wave devices config.
Expected behaviour:  These entities should not show in the UI.
Actual behaviour: In the States UI, they are hidden as expected.
In the Lovelace UI, these entities are displayed

**Javascript errors shown in the web inspector (if applicable):**
```
```
No Errors given.
**Additional information:**

If I revert to states UI, the hidden entities are hidden as expected.  Issue seems to only be with the Lovelace UI.
Thanks

**Comment by iantrich** [comment] 2019-02-14 02:05
duplicate of https://github.com/home-assistant/home-assistant-polymer/issues/2635

**Closed by iantrich** 2019-02-14 02:05 UTC
