### ISSUE TITLE
Support for password managers

### ISSUE THREAD

**Issue by rosch100** [home-assistant/home-assistant-polymer#4643] opened 2020-01-29 15:35 UTC
## The request
When browsing the login page on Windows, MacOS or iOS, a password manager is not able to auto-fill the username and password fields. Please enable the frontend to make use of this useful functionality.
It does not work with the built-in (Windows Edge, MacOS, iOS Safari) password manager or LastPass (Chrome, Firefox).

**Comment by balloob** [comment] 2020-01-30 07:07
Duplicate of #1622

**Closed by balloob** 2020-01-30 07:07 UTC
Labels: feature request
