### ISSUE TITLE
Inconsistent display of temperature graphs in multiple browsers.

### ISSUE THREAD

**Issue by gb53smith** [home-assistant/home-assistant-polymer#781] opened 2018-01-04 01:48 UTC
**Originally reported here:**
https://github.com/home-assistant/home-assistant/issues/10193
Now at HA v0.60.0 with no fix. 
Running hass.io on a Raspberry PI.

**Symptoms:**
When I click on a climate or temperature sensor component, the graph is missing on the first attempt.
Successive subsequent attempts always work.
After and idle period, the next attempt fails, followed again by successes. 

**Observed on these platforms and browsers:**
Windows 10 PC :  Chrome and Firefox
Iphone (iOS 11.2.1):  Safari and the iOS App

**Comment by honcheng** [comment] 2018-01-06 00:13
It's consistently not showing up for me in HA 0.60.0 Mac/iOS Safari. Works fine in Chrome. 
No success even after some idle time. Affects all graphs, including history_graph.

**Comment by alexanderVonBergner** [comment] 2018-01-07 15:46
I'm having the same problem. The graph shows fine on the Home Assistant iOS App on my iPhone, but the graph is not showing on the frontend in Safari on macOS. In fact the whole "History Tab" does not work anymore since adding my Climate Device.
Using Hassbian 0.60.1 on Raspberry Pi 3

**Comment by gb53smith** [comment] 2018-01-21 06:54
Seems to be fixed in hassio 0.61.1
If others confirm I will close this issue.

**Comment by OttoWinter** [comment] 2018-01-21 08:22
Can confirm it is fixed.

**Comment by alexanderVonBergner** [comment] 2018-01-21 08:41
Can not confirm.
I tried the following configurations:
MacBook:
macOS 10.13.2 with Safari 11.0.2: **does not work**
macOS 10.13.2 with Chrome 63.0: does work
macOS 10.13.2 with Firefox 57.0.4: does work
iPhone:
iOS 11.2.2 with Safari: does work
iOS 11.2.2 with Home Assistant App: does work

From my perspective the only platform having trouble seems to be macOS with Safari installed.

**Comment by andrey-git** [comment] 2018-01-21 08:51
If someone has a paid account at browserstack I can take a look.

**Comment by OttoWinter** [comment] 2018-01-23 17:18
Ok, I can confirm that it **does not** work with Safari 11.0.1 on macOS 10.13.1 though it does work with Chrome 63.0 and Firefox 57.0.1
On Android 8.1.0 it also works in Chrome 63.0 and the Home Assistant App (which, AFAIK is just using Chrome through the WebView API)
Probably doesn't matter much, but my Home Assistant instance is running inside a docker container through nginx, which is in another container.

**Comment by NovapaX** [comment] 2018-03-09 13:40
this should be fixed with: https://github.com/home-assistant/home-assistant-polymer/pull/950

**Closed** 2018-03-09 13:49 UTC

**Comment by alexanderVonBergner** [comment] 2018-03-10 11:43
Can confirm it is fixed with v0.65.1. Great!
