### ISSUE TITLE
Toast notification obstructs view

### ISSUE THREAD

**Issue by reef-actor** [home-assistant/home-assistant-polymer#2682] opened 2019-02-05 11:10 UTC
**Home Assistant release with the issue:**
0.86.4

**Description of problem:**
On performing an action such as turning on a switch, a useful toast notification appears to confirm that the service has been successfully called.  The positioning of this notification at the bottom of the display can obstruct controls until the notification times out.  This is particularly noticeable on mobile with the entities card.

Suggestion to move toast location to the top of the screen where space is reserved for the view tab icons?

**Comment by iantrich** [comment] 2019-03-07 19:43
fixed in 0.89

**Closed by iantrich** 2019-03-07 19:43 UTC

**Comment by vapuri** [comment] 2019-03-26 17:54
I noticed that the toast notifications don’t work for me any more when I toggle a switch or lock/unlock button. Wondering what the intended behavior is supposed to be as a result of this fix. I don’t see a notification at the top of the screen either. Thanks!

**Comment by iantrich** [comment] 2019-03-26 20:15
Toast notifications or only displayed when the service call fails now
