### ISSUE TITLE
Stuck on loading data with oAuth

### ISSUE THREAD

**Issue by flavio20002** [home-assistant/home-assistant-polymer#1680] opened 2018-09-19 15:34 UTC
**Home Assistant release with the issue:**
0.77.3

**Last working Home Assistant release (if known):**
0.74.2

**Browser and Operating System:**
Chrome 69.0.3497.92
MacOs 10.13.6

**Description of problem:**
I upgraded from 0.74.2 to 0.77.3 and I enabled oAuth authentication by creating a user. If i login with that user, and I save the session, i correctly see access token and refresh token in the storage section of the browser. If i return to the page after one hour or so, the site stuck on "loading" data, until i press refresh on the browser. In the web inspector I see following errors. The problem doesn't occur if use legacy API password access. Thanks for the support.

**Javascript errors shown in the web inspector (if applicable):**
```
Uncaught (in promise) TypeError: Failed to execute 'fetch' on 'ServiceWorkerGlobalScope': 'only-if-cached' can be set only with 'same-origin' mode
    at Object.<anonymous> (workbox-core.prod.js:1)
    at Generator.next (<anonymous>)
    at n (workbox-core.prod.js:1)
    at self.babelHelpers.asyncToGenerator (workbox-core.prod.js:1)
    at new Promise (<anonymous>)
    at Object.self.babelHelpers.asyncToGenerator (workbox-core.prod.js:1)
    at Object.workbox.core.j.fetch (workbox-core.prod.js:1)
    at workbox-strategies.prod.js:1
    at Generator.next (<anonymous>)
    at n (workbox-core.prod.js:1)
```

**Comment by balloob** [comment] 2018-09-21 11:16
That JS error is a red herring. It's caused by a bug in Chrome in combination with service workers.

Please clear your cache and your service workers or try in incognito mode.

**Comment by balloob** [comment] 2018-10-22 18:33
Going to close this as it's old. You can open a new one if still happening.

**Closed by balloob** 2018-10-22 18:33 UTC
