### ISSUE TITLE
History graph out of sync

### ISSUE THREAD

**Issue by ArtHome12** [home-assistant/home-assistant-polymer#4819] opened 2020-02-10 06:49 UTC
## The request

  Error - out of sync due to different scaling. I have been observing this problem for a long time, several months and it does not disappear.
The history graph y-axis labels results in the x-axis being compressed a tad to the right, so it doesn’t line up with the x-axis in the binary graph.

## Additional information
Screenshot and more info https://community.home-assistant.io/t/history-graph-out-of-sync-bug-report/170509

**Comment by bramkragten** [comment] 2020-02-10 09:19
Duplicate of #3707

**Closed by bramkragten** 2020-02-10 09:19 UTC
Labels: feature request
