### ISSUE TITLE
History Graph color palette

### ISSUE THREAD

**Issue by dgomes** [home-assistant/home-assistant-polymer#1122] opened 2018-04-24 12:42 UTC
**Home Assistant release with the issue:** 0.67

**Last working Home Assistant release (if known):** before chartjs 

**Browser and Operating System:** All browsers

**Description of problem:** Some history graphs are impossible to read. See the example:

https://imgur.com/JVcAFDi

This history graph has very thin lines for when the doors are open. Before using charts the color palette made it possible to visually pin where the door was open, now it's just impossible...

**Javascript errors shown in the web inspector (if applicable):**
```

```

**Additional information:**

I see 2 options: 
- Change the color palette based on the device type
- Add a configuration option, so users can change the colours themselves

**Comment by fanaticDavid** [comment] 2018-04-24 12:44
FYI: related to or even duplicate of #1094

**Closed** 2018-04-24 12:44 UTC
