### ISSUE TITLE
Add support for localization of UI strings

### ISSUE THREAD

**Issue by micw** [home-assistant/home-assistant-polymer#155] opened 2016-11-12 09:57 UTC
Most strings are hardcoded. Strings should come from a centralized source to allow localization. Locale should be determined by browser locale.

Examples: "Sun", "Rising", "Setting".

IMO localization would improve uasbility for non-english users a lot with only little work. As soon as we have localization implemented, the community will usually provide translations within a short time.

**Comment by fabaff** [comment] 2016-11-12 12:31
Feature requests are tracked in the forum.

Duplicate of https://community.home-assistant.io/t/localization-l10n/470

**Closed by fabaff** 2016-11-12 12:31 UTC
Labels: duplicate
