### ISSUE TITLE
weather cards show incorrect windspeed/unit

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/home-assistant-polymer#2482] opened 2019-01-15 15:39 UTC
**Home Assistant release with the issue:**

**Last working Home Assistant release (if known):**
not sure if at all

**Browser and Operating System:**

Safari/Chrome/Firefox Mac iPhone
**Description of problem:**

at least 2 weather cards (Buienradar and Darksky) show the incorrect windspeed, Open Weather Map shows correctly. This is both in Lovelace and regular HA

All indiviual sensors of these platforms are in m/s (meters, not miles). The cards show km/u but use the windspeed in m/s. Should either be multiplied by 3.6 to get km/u (using metric here) or the correct unit should be displayed:

**Javascript errors shown in the web inspector (if applicable):**
```

```

**Additional information:**
![schermafbeelding 2019-01-15 om 16 23 04](https://user-images.githubusercontent.com/33354141/51191166-22fb1080-18e4-11e9-81f3-8a1995d73fde.jpg)
![schermafbeelding 2019-01-15 om 16 23 14](https://user-images.githubusercontent.com/33354141/51191167-22fb1080-18e4-11e9-9746-69147efad2cf.jpg)

**Comment by bramkragten** [comment] 2019-01-15 15:49
This should be fixed in the backend, all weather platforms should return the same unit... The frontend doesn't know what unit the value is in.

**Comment by Mariusthvdb** [comment] 2019-01-15 15:51
yes, so what should we do? Other the file this issue?

**Comment by bramkragten** [comment] 2019-01-15 15:55
Create an architecture issue

**Comment by Mariusthvdb** [comment] 2019-01-15 15:57
Seems important enough the devs should take this to the correct place to discuss and develop to a solution.... 
If this is not it.
But, where would that be?

**Comment by bramkragten** [comment] 2019-01-15 16:00
Like I said, in the architecture repo https://github.com/home-assistant/architecture

**Comment by Mariusthvdb** [comment] 2019-01-15 20:09
I now found this https://github.com/home-assistant/home-assistant/issues/16793#issuecomment-454526140

Same issue , still not solved?

**Comment by balloob** [comment] 2019-01-15 22:20
Duplicate of https://github.com/home-assistant/home-assistant/issues/20142

**Closed by balloob** 2019-01-15 22:20 UTC

**Comment by Mariusthvdb** [comment] 2019-01-16 16:41
@balloob Please reopen: this is not a duplicate, since the referenced issue talks about Lovelace only, and this issue is both regular and Lovelace .
