### ISSUE TITLE
Z-wave config panel -> first item on long list hides under the blue header

### ISSUE THREAD

**Issue by quammy** [home-assistant/home-assistant-polymer#1729] opened 2018-10-03 14:14 UTC
**Home Assistant release with the issue:** 0.79.3

**Last working Home Assistant release (if known):**

**Browser and Operating System:** Chrome on Win10

**Description of problem:** When opening a long list on the Z-wave config panel (like nodes list), the first item is hidden under the blue header. I can see the first item only if decreasing screen size to 80%.
BTW, when opening a list it does show for a split of a second and then readjust and disappears.

100%:
![image](https://user-images.githubusercontent.com/3137488/46416197-ba6e9600-c72f-11e8-9fe1-ebdf3735bbc7.png)

80%:
![image](https://user-images.githubusercontent.com/3137488/46416161-a460d580-c72f-11e8-8873-9d3974a118b8.png)

**Javascript errors shown in the web inspector (if applicable):**
```

```

**Additional information:**

**Comment by cgarwood** [comment] 2018-10-05 12:18
Duplicate of #881

**Closed by cgarwood** 2018-10-05 12:18 UTC
