### ISSUE TITLE
Home assistan issue with Firefox 57 and Lastpass

### ISSUE THREAD

**Issue by fiasko** [home-assistant/home-assistant-polymer#698] opened 2017-11-29 10:35 UTC
When the Firefox 57 update came and FF57 compatible LastPass browser extension, the Home Assistan UI stopped working. When LastPass extension is disabled Home Assistant works perfectly, but when it's enabled, it stops working. If I haven't logged in to Home Assistan, I can't get past the Login screen. If I have logged in session in Home Assistant, the UI is blank when LastPass is enabled.

I am using Home Assistant 0.58.1 and I have tested both with and without the ?latest parameter in Home Assistant.

This is obviously closely related to LastPass extension and I've investigated the issue with help of LassPass customer support.

**Comment by andrey-git** [comment] 2017-11-29 13:13
This is a duplicate of #448

**Comment by NovapaX** [comment] 2018-04-05 07:42
Closing. We added a workaround for this in #811 
If this is still an issue bother Lastpass first to fix their extension 😉

**Closed by NovapaX** 2018-04-05 07:42 UTC
