### ISSUE TITLE
Entity button tap action service disappears when reopening editor.

### ISSUE THREAD

**Issue by bigcookie** [home-assistant/home-assistant-polymer#3093] opened 2019-04-15 14:27 UTC
**Home Assistant release with the issue:**
0.91

**Last working Home Assistant release (if known):**

**UI (States or Lovelace UI?):**
Coudlnt find the information in dev tools info. As I dont use anything else than the graphical UI, I think it is Lovelace UI.

**Browser and Operating System:**
Latest Chrome, Firefox, Safari on MacOS

**Description of problem:**
I used an entity button card created from the WebUI and filled out the needed data in the UI. Toggling editor mode revealed the following:

entity: script.squeezebox_all_turnoff
hold_action:
  action: none
icon: 'mdi:power'
name: Turn off ALL Squeezeboxes
tap_action:
  action: call-service
  service: 'script.turn_on'
type: entity-button

Saving and testing revealed, that all is working. BUT when opening editing mode again for this card, the tap_action service "script.turn_on" disappears. Toggling editor mode reveals:

entity: script.squeezebox_all_turnoff
hold_action:
  action: none
icon: 'mdi:power'
name: Turn off ALL Squeezeboxes
tap_action:
  action: call-service
  service: ''
type: entity-button

Now the card is calling weirdly several scripts together (probably like "all"), which is called "play_goodmorningmessage", then it is executing the correct script. When adding the missing service, it works again.
-> I changed now to the entities card. This works as expected.

**Additional information:**
The configuration scripts are split, which might be an issue. I added to configuration.yaml:

```
script: !include_dir_merge_named scripts
```

and in the subfolder "scripts", I placed several files, each with ONE script in it. List of files:

```
/config/scripts/alert_washingmachine.yaml
/config/scripts/goodmorning_message.yaml
/config/scripts/squeezebox.yaml
/config/script/startup_set_presence.yaml
```

each script looks similar to this:

```
squeezebox_all_turnoff:
  sequence:
  - service: media_player.turn_off
    entity_id:
      - media_player.squeezebox_kueche
      - media_player.squeezebox_wz
      - media_player.squeezebox_gastbad
      - media_player.squeezebox_bad
      - media_player.squeezebox_az
      - media_player.squeezebox_kz
      - media_player.squeezebox_sz
```

another one, which gets executed wrongly as written above - I removed the MAC addresses:

```
play_goodmorningmessage:
  alias: "Nachricht: Guten Morgen"
  sequence:
    - service: shell_command.playlist_save_sb
      data_template:
        mac: 'MACADR' # kitchen
        volume: '55'
    - service: shell_command.playlist_save_sb
      data_template:
        mac: 'MACADR' # bathroom
        volume: '45'
    - service: tts.google_say
      entity_id: media_player.squeezebox_kueche, media_player.squeezebox_bad
      data_template:
        message: >
          {% if now().strftime("%H")|int < 12 %}
            Guten Morgen.
          {% elif now().strftime("%H")|int < 18 %}
            Guten Tag.
          {% else %}
            Guten Abend.
          {% endif %}
            Es ist {{states.sensor.dark_sky_summary.state}} bei {{states.sensor.dark_sky_temperature.state|round}} Grad.
          {% if 'Morgen' not in states('sensor.dark_sky_hourly_summary') %}
            Heute
          {% endif %}
          {{states.sensor.dark_sky_hourly_summary.state|replace(".", "")}}, mit einer Tageshöchsttemperatur von {{states.sensor.dark_sky_daytime_high_temperatuu
re_0d.state|round}} Grad.
          {% if states.sensor.dark_sky_precip_probability_1h.state|int > 50 and now().weekday() in (0,1,2,3,4) %}
            Für den Weg zur Arbeit mit dem Fahrrad besser eine Regenhose anziehh
en, die Regenwahrscheinlichkeit in 1 Stunde beträgt {{states.sensor.dark_sky_prr
ecip_probability_1h.state|round}} Prozent.
          {% endif %}
    - service: shell_command.playlist_restore_sb
      data_template:
        mac: 'MACADR'
    - service: shell_command.playlist_restore_sb
      data_template:
        mac: 'MACADR'

  # bad: MACADR
  # gastbad: MACADR
  # kueche: MACADR
  # kz: MACADR
  # sz: MACADR
  # wz: MACADR
```

I found as well the following in the log:

```
Not passing an entity ID to a service to target all entities is deprecated. Update your call to script.turn_on to be instead: entity_id: all
```

**Comment by iantrich** [comment] 2019-04-15 14:29
Duplicate of https://github.com/home-assistant/home-assistant-polymer/issues/2645

**Closed by iantrich** 2019-04-15 14:29 UTC
