### ISSUE TITLE
Changing temperature of the climate sensor causes it to show a rounding error

### ISSUE THREAD

**Issue by michaelarnauts** [home-assistant/home-assistant-polymer#1798] opened 2018-10-17 18:11 UTC
**Home Assistant release with the issue:** 0.80

**Last working Home Assistant release (if known):** N/A

**Browser and Operating System:** Windows 10, happens on latest chrome and firefox.

**Description of problem:**
Image says more then 1000 words:
![image](https://user-images.githubusercontent.com/1193779/47106787-d56cfa00-d247-11e8-920f-3e8e30a6bd57.png)

I believe this is a purely frontend issue, since no call to the backend is made when the error occurs.

My temperature is set to 21 degrees (celcius). When I increase it to 21.1, it's fine, when I click again fast (before the `climate/set_temperature` is called), it shows "21.200000000000003 °C", after a second or so, the following call to the backend is made:

```
{"type":"call_service","domain":"climate","service":"set_temperature","service_data":{"temperature":21.200000000000003,"entity_id":"climate.heating"},"id":22}
```

Again, after a few ms, the event comes in from the backend that sets the temperature to the rounded value (21.2) again.

**Javascript errors shown in the web inspector (if applicable):**
```

```

**Additional information:**

**Comment by milanvo** [comment] 2018-10-24 17:03
I can confirm this. It is purely frontend issue caused by rounding error of floating point variable within increment/decrement methods here:
https://github.com/home-assistant/home-assistant-polymer/blob/cf2171ece107e93a25324f01176e0f622482770e/src/components/ha-climate-control.js#L100

Testing dirty fix now, which works. I am not big JS programmer unfortunately 😉, considering creating PR.

**Comment by iantrich** [comment] 2018-12-13 19:40
Anyone care to check this in Lovelace in an `entities` card?

**Comment by milanvo** [comment] 2018-12-21 14:55
@iantrich is there option to specify `step` in Lovelace `therostat` card ? It looks like only integer temperature can be set.

**Comment by iantrich** [comment] 2018-12-21 15:52
@milanvo I have a PR open to change that: https://github.com/home-assistant/home-assistant-polymer/pull/2369

The default behavior will be to by integer for `F` and 0.5 for `C` unless the device has the attribute `target_temp_step` set, which then takes precedence.

**Comment by milanvo** [comment] 2018-12-21 16:10
Great, I will check when merged

**Closed** 2019-01-03 22:07 UTC
Labels: in progress, states
