### ISSUE TITLE
Clicking top-level group shows items from the first nested group

### ISSUE THREAD

**Issue by jackwilsdon** [home-assistant/home-assistant-polymer#768] opened 2017-12-28 18:44 UTC
*Copied from home-assistant/home-assistant#11338*

---

Make sure you are running the latest version of Home Assistant before reporting an issue.

You should only file an issue if you found a bug. Feature and enhancement requests should go in [the Feature Requests section](https://community.home-assistant.io/c/feature-requests) of our community forum:

**Home Assistant release (`hass --version`):** 0.60.0

**Python release (`python3 --version`):** Python 3.6.3

**Component/platform:** Group

**Description of problem:** Clicking the header of a group which contains another group opens a dialog containing all of the children from the first child group, as well as the first child group itself and all other child groups.

**Expected:** Only the immediate children of the group clicked would be visible.

**Problem-relevant `configuration.yaml` entries and steps to reproduce:**
```yaml
frontend:

group:
  default_view:
    name: Default View
    view: true
    entities:
      - group.parent
  parent:
    name: Parent
    entities:
      - group.child_1
      - group.child_2
  child_1:
    name: Child 1
    entities:
      - input_boolean.switch_1
      - input_boolean.switch_2
  child_2:
    name: Child 2
    entities:
      - input_boolean.switch_3
      - input_boolean.switch_4

homeassistant:
  name: Example HASS

http:

input_boolean:
  switch_1:
    name: "Switch #1"
  switch_2:
    name: "Switch #2"
  switch_3:
    name: "Switch #3"
  switch_4:
    name: "Switch #4"
```

1. Click "Parent" heading
2. Observe that "Switch <span>#</span>1" and "Switch <span>#</span>2" are visible in the list

**Additional info:**

After some investigation, it looks like it's something to do with the `more-info-dialog` Polymer component, although I don't have enough of an understanding of Polymer to investigate it further.

Quote from @tschmidty69 in home-assistant/home-assistant#11338;

> Switch 1 and Switch 2 are part of the groupedControlDetails which, to be honest, I don't particularly understand why they are displayed this way. It basically picks the first element/group and shows the details for that for the card.

**Screenshot of the issue;**

![parent](https://user-images.githubusercontent.com/1843197/34398943-dbef123c-eb7a-11e7-87ba-65a838037322.png)

**Comment by ciotlosm** [comment] 2018-01-02 20:32
I was able to reproduce this with device_tracker (very annoying), but I never logged it.

**Comment by ciotlosm** [comment] 2018-01-02 21:29
@jackwilsdon I was able to track down the bug, but not sure how "states" got to be changed while being computed. I noticed with debugger many calls to computeStates so I assumed "states" was being changed, so I renamed it which stopped the problem.

**Comment by balloob** [comment] 2018-01-03 00:00
The problem here is that we show the "more info controls" of the first entity if all entities share the same domain. So in the case of 'group' we should just not show it.

**Comment by ciotlosm** [comment] 2018-01-03 17:46
@balloob If the shared domain is 'group' but all the sub-entities are 'switch' than a more info control will still make sense I think.

**Comment by jackwilsdon** [comment] 2018-01-03 19:08
> If the shared domain is 'group' but all the sub-entities are 'switch' than a more info control will still make sense I think.

Would this not end up looking like it does in the original issue? Is there a reason we show the more info controls for the first entity if all entities are in the same domain?

**Comment by tschmidty69** [comment] 2018-01-03 19:14
I agree with crusader727 that it should look like this in the moreinfo:
```
parentgroup (control)
    sub group 1 (control)
        switch 1  (control)
        switch 2 (control)
    sub group 2 (control)
        switch 3 (control)
        switch 4 (control)
```
We are asking for more info, it doesn't make sense to just show the original card again with just the groups but organizing it this way would be the most useful.

**Comment by balloob** [comment] 2018-01-07 05:37
@jackwilsdon It's because if you open a group of lights, you probably want to control them as lights instead of just seeing a list to turn on/off.

@tschmidty69 the issue here can be fixed with a bug fix. What you're proposing is new feature

**Closed** 2018-01-07 21:25 UTC
