### ISSUE TITLE
Hass.io page empty

### ISSUE THREAD

**Issue by ekt-** [home-assistant/home-assistant-polymer#889] opened 2018-02-13 22:32 UTC
After 62.1, Hass.io page is empty
Perdures on 63.1
Refreshing the page multiple times (F5) eventually populates the page, but without the theme applied
Reproduced on Chrome 64 and Firefox Quantum

All other pages are fine, with theme correctly applied

releated log
`https://x.x.x.x:8123/frontend_latest/panels/ha-panel-hassio-ad7aa9a6055f74475fd3ba2c00bfe512.html:1:829 Uncaught TypeError: Cannot read property 'setProperties' of null
11:19 PM components/system_log/__init__.py (ERROR)`

**Comment by ekt-** [comment] 2018-02-15 07:50
I uninstalled LastPass and ucBlock, now the page shows up. But still not themed.

**Comment by c727** [comment] 2018-02-15 13:17
Duplicate of #848
Themes are fixed but not packaged yet

**Closed by c727** 2018-02-15 13:17 UTC
