### ISSUE TITLE
Conditional card invisible in editor

### ISSUE THREAD

**Issue by caro-coder** [home-assistant/home-assistant-polymer#3625] opened 2019-09-05 05:56 UTC
**Home Assistant release with the issue:**
0.98.3

**Last working Home Assistant release (if known):**
None

**UI (States or Lovelace UI?):**
Lovelace UI

**Browser and Operating System:**
Newest Firefox and Windows 10 (not browser specific)

**Description of problem:**
When editing a conditional card in the Lovelace UI editor, the card might be invisible if the condition is false. While I like that, because I can test the conditions that way, it would be nice if there's a switch in the editor to bypass the conditions so you can see the card anyway.
For now I have to modify the conditions to preview my card, which is especially annoying if you have many of them.

**Javascript errors shown in the web inspector (if applicable):**
```

```

**Additional information:**

**Comment by iantrich** [comment] 2019-09-26 04:48
duplicate of yourself ;) https://github.com/home-assistant/home-assistant-polymer/issues/3624

**Closed by iantrich** 2019-09-26 04:48 UTC
