### ISSUE TITLE
New Charts.js y-axis should start in zero

### ISSUE THREAD

**Issue by pxpto** [home-assistant/home-assistant-polymer#1015] opened 2018-03-21 17:47 UTC
In this example there are only positive values, but the y-axis starts in -2000.

![image](https://user-images.githubusercontent.com/5114388/37727457-caba026e-2d2f-11e8-975c-e67312a310f8.png)

**Comment by arsaboo** [comment] 2018-03-21 17:50
If it starts from 0, most of the values will be very close to the margin. I am guessing, the buffer is added to avoid such cases.

**Comment by pxpto** [comment] 2018-03-21 17:56
Maybe that's right. But in my example it uses 25% of the chart y-axis for that. It shouldn't use that much space.
And what if the chart touches the margin? Would that be a problem? It should still be visible...

**Comment by NovapaX** [comment] 2018-03-21 18:05
Agree, there's no need for the margin (at least not that large.)

**Comment by VDRainer** [comment] 2018-03-26 17:51
I think the margin should be larger or there should be more space for the value card.
If the values are close to the bottom you can't read the values and the graph shows an unusable scrollbar at the right edge.
![auswahl_085](https://user-images.githubusercontent.com/26381449/37923236-f2cac204-312e-11e8-84d3-45e1cab4dfab.png)

**Comment by pxpto** [comment] 2018-03-27 09:04
I'm runnin 0.65.6 and if I scroll the chart down to align the "0" in the bottom I get normal charts:

![image](https://user-images.githubusercontent.com/5114388/37957469-ec64bf06-31a5-11e8-80aa-b52bed99ad29.png)

![image](https://user-images.githubusercontent.com/5114388/37957475-f125adb6-31a5-11e8-8b97-b8bff361e995.png)

**Comment by VDRainer** [comment] 2018-03-27 10:33
Maybe this affects only the [history_graph](https://www.home-assistant.io/components/history_graph/) component, when the graphs are displayed in a card?

**Comment by NovapaX** [comment] 2018-03-27 10:38
No this affects all charts, as the rendering is exactly the same.
I'm currently looking at the chart, but the loading message, erratic (scroll-blocking) zooming, and wierd panning take priority over this 'margin' issue.

**Comment by fanthos** [comment] 2018-04-03 08:00
I added 1% of max - min buffer to both max and min data. The chart may not drawing lines correctly if min = 0 and y axis starts at 0.

**Comment by NovapaX** [comment] 2018-04-03 08:04
Yes, I've seen that in the chart code. The problem is that it triggers the chart to add a complete 'tick' as margin...

**Comment by fanthos** [comment] 2018-04-03 08:07
I think there should have better way to adding the buffer, or just change minimal tick count to large number?

**Comment by NovapaX** [comment] 2018-04-14 22:54
closed in #1077

**Closed by NovapaX** 2018-04-14 22:54 UTC
Labels: element: chart
