### ISSUE TITLE
Sonos album art when using Line-In needs to be fixed

### ISSUE THREAD

**Issue by arsaboo** [home-assistant/home-assistant-polymer#153] opened 2016-11-07 16:19 UTC
Following the Sonos recent album art fixes by @bjarniivarsson, which I love, there is one unintended side-effect. The album art when Sonos is using Line-IN (on Play:5) is messed up:

![image](https://cloud.githubusercontent.com/assets/18319734/20065412/023aaf5a-a4dc-11e6-895f-4e28bba521f8.png)

When I pause the audio, I get a similar card:

![image](https://cloud.githubusercontent.com/assets/18319734/20065414/0658f81c-a4dc-11e6-95f1-844994eb9896.png)

I am guessing, the problem is only when using line-in as the audio source.

**Comment by johnconn73** [comment] 2016-11-16 21:18
I agree.  It'd be great to have a more compact view of each of the SONOS widgets, too.  BTW, I think the behaviour above is across all SONOS devices.  I have a Playbar, Play3 and a Play5 and they all present as @arsaboo describes with large white panels above - regardless of what's playing or not.  I think a more horizontal display would be preferable so it takes up less vertical space ie cover art placeholder to the left, controls to the right?

**Comment by arsaboo** [comment] 2016-11-16 21:20
As I recall, @bjarniivarsson's original intent behind these large boxes was to give enough space to the album art. Unfortunately, when when there is no album art, these large empty boxes look ugly.

**Comment by johnconn73** [comment] 2016-11-16 21:25
Understood. And that makes sense for many.  Perhaps alternative displays for those that need more or less cover art visible.  Cover art is a nice touch, but for me it's more important to know just what is playing and where rather than how the album art looks.  I really should learn to develop so I can contribute...

**Comment by bjarniivarsson** [comment] 2016-11-17 06:27
That you are getting a white box instead of album art is definately a bug. The white background should only appear if there is some album art to display on top of it (otherwise you should get a blue background with an icon). As I don't have a SONOS device with a line in (only have Play 1/3 speakers) it is hard for me to test, but I have a pretty good idea how to fix this, will have a look tonight.

Regarding the size of the player, I't should show as more compact when not playing music (and when no album art is available). I did think about solutions where the album could be on the left, with album info/controls on the right, but one of the problems is that some media players have wider album art (video players). I'll play around with the HTML/CSS, but I think it will be hard to find something that everyone is happy with.

**Comment by arsaboo** [comment] 2016-11-17 19:34
Thanks @bjarniivarsson!!

**Comment by mihalski** [comment] 2016-11-27 06:08
How about a view with no album art at all as an option? I noticed that this is exactly what I get when the Sonos Playbar is in TV mode.

Just something like:

`album_art: false`

My Yamaha A/V Receiver seems to have this compact view without album art by default.

**Comment by mihalski** [comment] 2016-11-27 08:08
FWIW:

https://someimage.com/Xqpymiy

**Comment by balloob** [comment] 2017-01-30 08:08
This is not a bug in the frontend but in the Sonos platform. As @bjarniivarsson notes, the component should not show any album art if there is none. This is what can also be observed in the code here: https://github.com/home-assistant/home-assistant-polymer/blob/master/src/cards/ha-media_player-card.html#L278-L279

The bug with Sonos is that when it doesn't have album art, it should return `None` from property `media_image_url`.

Closing this as it is not frontend related.

**Closed by balloob** 2017-01-30 08:08 UTC
