### ISSUE TITLE
TypeError: this._meta.byKey is not a function in Firefox 

### ISSUE THREAD

**Issue by corneyl** [home-assistant/home-assistant-polymer#448] opened 2017-10-09 09:43 UTC
As reported in the main home-assistant repository (home-assistant/home-assistant#8966) there is a problem with accessing the UI using firefox since v0.51.1. This problem is not fixed, although the previous issue is closed: #428. It seems also to be a problem when using Edge: #434. 

Imho this should get priority, as a lot of users cannot access the frontend at all using their favourite browser.

```
11:37:38.355 TypeError: this._meta.byKey is not a function 1 data:Polymer(%7Bis%3A%22iron-icon%22%2Cproperties%3A%7Bicon%3A%7Btype%3AString%7D%2Ctheme%3A%7Btype%:1:800
	_updateIcon https://ha.domain.com:8080/static/frontend-7e13ce36d3141182a62a5b061e87e77a.html-82.js:1:800
	_iconChanged https://ha.domain.com:8080/static/frontend-7e13ce36d3141182a62a5b061e87e77a.html-82.js:1:448
	k https://ha.domain.com:8080/static/frontend-7e13ce36d3141182a62a5b061e87e77a.html-11.js:1:6681
	a https://ha.domain.com:8080/static/frontend-7e13ce36d3141182a62a5b061e87e77a.html-11.js:1:1854
	e https://ha.domain.com:8080/static/frontend-7e13ce36d3141182a62a5b061e87e77a.html-11.js:1:1618
	value https://ha.domain.com:8080/static/frontend-7e13ce36d3141182a62a5b061e87e77a.html-11.js:1:13410
	value https://ha.domain.com:8080/static/frontend-7e13ce36d3141182a62a5b061e87e77a.html-9.js:1:5631
	value https://ha.domain.com:8080/static/frontend-7e13ce36d3141182a62a5b061e87e77a.html-11.js:1:13043
	value https://ha.domain.com:8080/static/frontend-7e13ce36d3141182a62a5b061e87e77a.html-12.js:1:4887
	value https://ha.domain.com:8080/static/frontend-7e13ce36d3141182a62a5b061e87e77a.html-25.js:1:2814
	value https://ha.domain.com:8080/static/frontend-7e13ce36d3141182a62a5b061e87e77a.html-26.js:1:2806
	value https://ha.domain.com:8080/static/frontend-7e13ce36d3141182a62a5b061e87e77a.html-9.js:1:5465
	value https://ha.domain.com:8080/static/frontend-7e13ce36d3141182a62a5b061e87e77a.html-11.js:1:12743
	value https://ha.domain.com:8080/static/frontend-7e13ce36d3141182a62a5b061e87e77a.html-11.js:1:12807
	value https://ha.domain.com:8080/static/frontend-7e13ce36d3141182a62a5b061e87e77a.html-12.js:1:5070
	value https://ha.domain.com:8080/static/frontend-7e13ce36d3141182a62a5b061e87e77a.html-11.js:1:12490
	value https://ha.domain.com:8080/static/frontend-7e13ce36d3141182a62a5b061e87e77a.html-11.js:1:13359
	value https://ha.domain.com:8080/static/frontend-7e13ce36d3141182a62a5b061e87e77a.html-9.js:1:5631
	value https://ha.domain.com:8080/static/frontend-7e13ce36d3141182a62a5b061e87e77a.html-11.js:1:13043
	value https://ha.domain.com:8080/static/frontend-7e13ce36d3141182a62a5b061e87e77a.html-12.js:1:4887
	value https://ha.domain.com:8080/static/frontend-7e13ce36d3141182a62a5b061e87e77a.html-25.js:1:2814
	value https://ha.domain.com:8080/static/frontend-7e13ce36d3141182a62a5b061e87e77a.html-26.js:1:2806
	value https://ha.domain.com:8080/static/frontend-7e13ce36d3141182a62a5b061e87e77a.html-26.js:1:2806
	value https://ha.domain.com:8080/static/frontend-7e13ce36d3141182a62a5b061e87e77a.html-26.js:1:2806
	value https://ha.domain.com:8080/static/frontend-7e13ce36d3141182a62a5b061e87e77a.html-26.js:1:2806
	value https://ha.domain.com:8080/static/frontend-7e13ce36d3141182a62a5b061e87e77a.html-26.js:1:2806
	value https://ha.domain.com:8080/static/frontend-7e13ce36d3141182a62a5b061e87e77a.html-26.js:1:2806
	value https://ha.domain.com:8080/static/frontend-7e13ce36d3141182a62a5b061e87e77a.html-9.js:1:5465
	value https://ha.domain.com:8080/static/frontend-7e13ce36d3141182a62a5b061e87e77a.html-11.js:1:12743
	value https://ha.domain.com:8080/static/frontend-7e13ce36d3141182a62a5b061e87e77a.html-11.js:1:12807
	value https://ha.domain.com:8080/static/frontend-7e13ce36d3141182a62a5b061e87e77a.html-12.js:1:5070
	value https://ha.domain.com:8080/static/frontend-7e13ce36d3141182a62a5b061e87e77a.html-11.js:1:12490
	value https://ha.domain.com:8080/static/frontend-7e13ce36d3141182a62a5b061e87e77a.html-11.js:1:13359
	value https://ha.domain.com:8080/static/frontend-7e13ce36d3141182a62a5b061e87e77a.html-9.js:1:5631
	value https://ha.domain.com:8080/static/frontend-7e13ce36d3141182a62a5b061e87e77a.html-11.js:1:13043
	value https://ha.domain.com:8080/static/frontend-7e13ce36d3141182a62a5b061e87e77a.html-12.js:1:4887
	value https://ha.domain.com:8080/static/frontend-7e13ce36d3141182a62a5b061e87e77a.html-25.js:1:2814
	value https://ha.domain.com:8080/static/frontend-7e13ce36d3141182a62a5b061e87e77a.html-26.js:1:2806
	value https://ha.domain.com:8080/static/frontend-7e13ce36d3141182a62a5b061e87e77a.html-9.js:1:5465
	value https://ha.domain.com:8080/static/frontend-7e13ce36d3141182a62a5b061e87e77a.html-11.js:1:12743
	value https://ha.domain.com:8080/static/frontend-7e13ce36d3141182a62a5b061e87e77a.html-11.js:1:12807
	value https://ha.domain.com:8080/static/frontend-7e13ce36d3141182a62a5b061e87e77a.html-12.js:1:5070
	value https://ha.domain.com:8080/static/frontend-7e13ce36d3141182a62a5b061e87e77a.html-11.js:1:12490
	value https://ha.domain.com:8080/static/frontend-7e13ce36d3141182a62a5b061e87e77a.html-11.js:1:13359
	value https://ha.domain.com:8080/static/frontend-7e13ce36d3141182a62a5b061e87e77a.html-9.js:1:5631
	value https://ha.domain.com:8080/static/frontend-7e13ce36d3141182a62a5b061e87e77a.html-11.js:1:13043
	value https://ha.domain.com:8080/static/frontend-7e13ce36d3141182a62a5b061e87e77a.html-12.js:1:4887
	value https://ha.domain.com:8080/static/frontend-7e13ce36d3141182a62a5b061e87e77a.html-199.js:1:1442
	value https://ha.domain.com:8080/static/frontend-7e13ce36d3141182a62a5b061e87e77a.html-9.js:1:5465
	value https://ha.domain.com:8080/static/frontend-7e13ce36d3141182a62a5b061e87e77a.html-11.js:1:12743
	value https://ha.domain.com:8080/static/frontend-7e13ce36d3141182a62a5b061e87e77a.html-11.js:1:12807
	value https://ha.domain.com:8080/static/frontend-7e13ce36d3141182a62a5b061e87e77a.html-11.js:1:12490
	value https://ha.domain.com:8080/static/frontend-7e13ce36d3141182a62a5b061e87e77a.html-11.js:1:13359
	value https://ha.domain.com:8080/static/frontend-7e13ce36d3141182a62a5b061e87e77a.html-9.js:1:5631
	value https://ha.domain.com:8080/static/frontend-7e13ce36d3141182a62a5b061e87e77a.html-11.js:1:13043
	value https://ha.domain.com:8080/static/frontend-7e13ce36d3141182a62a5b061e87e77a.html-9.js:1:5465
	e https://ha.domain.com:8080/static/frontend-7e13ce36d3141182a62a5b061e87e77a.html-29.js:1:3557
	n https://ha.domain.com:8080/static/frontend-7e13ce36d3141182a62a5b061e87e77a.html-28.js:1:1447
	e https://ha.domain.com:8080/static/frontend-7e13ce36d3141182a62a5b061e87e77a.html-29.js:1:1441
	e https://ha.domain.com:8080/static/frontend-7e13ce36d3141182a62a5b061e87e77a.html-29.js:1:5719
	value https://ha.domain.com:8080/static/frontend-7e13ce36d3141182a62a5b061e87e77a.html-33.js:1:3582
	value https://ha.domain.com:8080/static/frontend-7e13ce36d3141182a62a5b061e87e77a.html-33.js:1:2484
	value/this.__renderDebouncer< https://ha.domain.com:8080/static/frontend-7e13ce36d3141182a62a5b061e87e77a.html-33.js:1:1871
	value/this._timer< https://ha.domain.com:8080/static/frontend-7e13ce36d3141182a62a5b061e87e77a.html-15.js:1:675
	<anonymous> https://ha.domain.com:8080/static/frontend-7e13ce36d3141182a62a5b061e87e77a.html-8.js:1:168
```

**Comment by corneyl** [comment] 2017-10-11 08:11
In v0.55 it seems to work, but one has to be certain to clear the browsers cache.

**Comment by corneyl** [comment] 2017-10-14 08:20
The strange thing is, when I reload using Ctrl+F5 it works. When I normally access the page, is doesn't. So it's not fixed, maybe something went wrong while building the package

**Comment by fortinj1354** [comment] 2017-10-20 15:16
This is definitely still broken in Firefox 57 on the latest home assistant version. No amount of clearing the cache/cookies and force refreshing works.

**Comment by mnoorenberghe** [comment] 2017-10-22 04:29
FWIW, I run Firefox Nightly (now at version 58) and I don't have this problem. Maybe try unregister the hass service worker on `about:serviceworkers`?

**Comment by fortinj1354** [comment] 2017-10-22 06:38
Actually now I'm getting a new exception
`Source map error: request failed with status 404
Resource URL: http://vm-homeassist:8123/static/webcomponents-lite.js
Source Map URL: webcomponents-lite.js.map`

This file definitely does not exist either on my install or on the home assistant repo, but it's not failing in chrome so I don't know why it wouldn't be working here.

**Comment by mnoorenberghe** [comment] 2017-10-22 06:42
Some notes:
* Service Workers only work over https but the error message included http://… so maybe you are loading the site over http?
* Source maps are for debugging only so that error shouldn't be related to whether HASS works or not

**Comment by fortinj1354** [comment] 2017-10-22 06:55
Ah, if the source maps don't matter then it is still just the "undefined error"

And that http request was directly to the home assistant vm, but I'm getting the same error when hitting it over https through a reverse proxy.

**Comment by sharpless** [comment] 2017-10-22 10:09
Using Firefox 57 on an old MacBook running El Capitan, have only set up home assistant for access on local network, ie no TLS for now and I have the same problem. Chrome works fine on the same computer.

**Comment by mnoorenberghe** [comment] 2017-10-22 20:56
For people having this issue:
* How are you installing hass?
* Does the problem happen in a clean Firefox profile: e.g. on macOS:
`mkdir /tmp/fx_release && /Applications/Firefox.app/Contents/MacOS/firefox --profile /tmp/fx_release`
* Does clearing the service worker cache for devtools work? 
![screen shot 2017-10-22 at 1 53 47 pm](https://user-images.githubusercontent.com/601139/31866188-9d107250-b730-11e7-89ab-71d55ffd2267.png)
* Make sure you're running a recent version of HASS

**Comment by durin42** [comment] 2017-10-22 22:06
Installing hass using `pip3 install ...` via ansible (my own playbooks)

Issue does not happen in a clean Firefox profile (Firefox 56, current stable)

Clearing the "cache storage" did not help. Nor did clearing "local storage" in the same part of the devtools.

**Comment by mnoorenberghe** [comment] 2017-10-22 22:09
ok, try in safe mode (Help > Restart with add-ons disabled) then to see if it's caused by an extension. Are you running in private browsing mode?

**Comment by durin42** [comment] 2017-10-22 22:10
Just tried turning off all extensions. By bisecting it, it's LastPass. 🤔

I'll see if I can figure out how to go file a bug with them.

**Comment by durin42** [comment] 2017-10-22 22:16
(This is the WebExtension version of LastPass that'll work with 57 and later, so hopefully they're attentive.)

**Comment by mnoorenberghe** [comment] 2017-10-22 22:17
Oh, weird, I was just going to recommend [the beta version](https://blog.lastpass.com/2017/10/lastpass-beta-firefox-57.html/).

**Comment by durin42** [comment] 2017-10-22 22:18
Yeah, that's what I've got installed, and as far as I can remember upgrading to the beta correlates in time with my homeassistant frontend woes.

**Comment by balloob** [comment] 2017-10-26 00:22
I am going to close this issue as it is not a problem of Home Assistant. We are responsible and are shipping a working frontend, we control exactly what we ship so that we know it works. It is not up to us to try to work around flaws in every extension for every browser ever. Instead,  extensions in browsers need to good citizens and should not break websites. Please report this to LastPass.

**Closed by balloob** 2017-10-26 00:22 UTC
Labels: help wanted

**Comment by durin42** [comment] 2017-10-26 00:23
I've done so. I'm not terribly optimistic that my report is making it to people empowered to fix the problem. :(

(Agree you shouldn't try to workaround their bugs tho.)

**Comment by durin42** [comment] 2017-11-02 00:04
For anyone following along at home:

>  I have filed a report to our developers for further review. But I cannot provide an estimated time for the fix as the plugin in still in beta.
>
>  Thank you for bringing this to our attention.

So I guess they'll fix it eventually.
