### ISSUE TITLE
New custom ui fallback causes custom cards to not display on initial load.

### ISSUE THREAD

**Issue by Bahnburner** [home-assistant/home-assistant-polymer#1671] opened 2018-09-17 21:25 UTC
**Home Assistant release with the issue:**
0.78

**Last working Home Assistant release (if known):**
0.77

**Browser and Operating System:**
Chrome 69 on Windows 10 pro
Chrome 70 beta on Mac OS Mojave
Chrome 70 beta on Android 8.0 Nougat

**Description of problem:**
Custom components to not appear in Lovelace on first load. User must use the "refresh" option in the overflow menu of nav bar, or change to another view and back. 

**Javascript errors shown in the web inspector (if applicable):**
```
none.
```

**Additional information:**
This is related to #1670

**Comment by Bahnburner** [comment] 2018-09-18 12:51
Correction. This issue is in 0.79dev0. Closing issue.

**Comment by balloob** [comment] 2018-09-18 12:53
Why did you close it? Is it still happening on dev?

**Comment by Bahnburner** [comment] 2018-09-18 12:56
I thought the issue was occurring in 0.78. I didn't realize docker had
pulled Dev instead. I downgraded from Dev to 0.78 and am not experiencing
it anymore.

**Comment by quthla** [comment] 2018-09-19 00:10
I can confirm this.

`TypeError: invalid assignment to const `i'[Weitere Informationen] create-card-element.js:64:27`

**Comment by balloob** [comment] 2018-09-19 08:19
![image](https://user-images.githubusercontent.com/1444314/45740370-6aeb7e80-bbf5-11e8-8235-db11aaa91107.png)

Can reproduce it. Happens only in prod builds. Seems to be caused by the minifier.

**Closed** 2018-09-19 09:32 UTC
Labels: in progress
