### ISSUE TITLE
Keep hamburger menu on mobile devices

### ISSUE THREAD

**Issue by riemers** [home-assistant/home-assistant-polymer#282] opened 2017-05-12 11:10 UTC
Current look on the mobile device shows the "home assistant" text on the top, while this is ok on the desktop version, it is uncommon on mobile device. So when you scroll up you see something in the order of:

![image](https://cloud.githubusercontent.com/assets/682041/25995714/f37dd486-3713-11e7-90f3-b02511914653.png)

Instead you would want the hamburger menu to stay regardless. Like:

![image](https://cloud.githubusercontent.com/assets/682041/25995726/06ae3104-3714-11e7-973a-bd42082d055e.png)

This would save space, and if you have a long list, you don't have to scroll back up to the top. 

If this is not wanted, then there should be an option to quicly go to the top. In most apps (ios) you can click on the top bar, where the time is and it will jump to the top.

This ofcourse is my personal preference, but i think it is a welcome addition.

**Comment by balloob** [comment] 2017-05-12 16:09
You can click on the active tab bar item to quickly scroll to the top.

But you're right that the menu item should stay visible

**Comment by riemers** [comment] 2017-05-15 13:50
It's not the end of the world, sadly i have no polymer skills as of yet. But if you say that its not straightforward i'am out of luck to be helpfull. Perhaps something for on the roadmap as a 'nice to have' or hackaton event.

On a side note, new features would be fun to have a donation button next to them for the coders. So if someone picks it up they could earn a few bucks as 'extra' if its not core functionality. Minus a % to a charity ofcourse.

**Comment by riemers** [comment] 2017-05-18 14:54
![image](https://cloud.githubusercontent.com/assets/682041/26208428/589e654e-3bea-11e7-9d5b-68203f69d9bb.png)

As a side note, if you use the mouse to slide open the menu on the left. The rest of the screen doesn't move to the right. Using the hamburger menu does. (belongs into the same category kind off)

**Comment by balloob** [comment] 2017-05-19 00:35
That's not a bug, that is expected behavior. Sliding the menu slides it over content. Using the hamburger menu toggles permanent visibility of the sidebar.

**Comment by cgarwood** [comment] 2018-10-18 19:30
I'm going to go ahead and close this for now since it would require restructuring and there's a fairly simple workaround to scroll to the top.

**Closed by cgarwood** 2018-10-18 19:30 UTC
Labels: Mobile

**Comment by riemers** [comment] 2018-10-18 20:49
Didn't knew it was still open no problem 👍
