### ISSUE TITLE
Temp Set Up from front-end in Generic Thermostat is by halves °C only (see also #22596)

### ISSUE THREAD

**Issue by AndrRap** [home-assistant/home-assistant-polymer#3109] opened 2019-04-21 15:31 UTC
Home Assistant release with the issue:

arch: armv6l
dev: false
docker: true
hassio: true
os_name: Linux
python_version: 3.7.2
timezone: Europe/Rome
version: 0.90.2
virtualenv: false

Last working Home Assistant release (if known):

Operating environment (Hass.io/Docker/Windows/etc.):
Hass.io/Docker/Raspberry Pi 1

Component/platform:
Generic Thermostat https://github.com/home-assistant/home-assistant/commit/038b1c1fc67ca33e0e242a27d6dc80ad7305b675

Description of problem:
Precision value and Target Temp can be set in configuration.yaml, as of PR #18317, with a precision of o.1°C but in the front end card only 0.5°C increment/decrement is accepted.
So if I set 19.6 in the configuration.yaml and I want to change it to different value using the slider in the front end, I can only set it to 19.0, 19.5, 20.0, 20.5, ... with a precision of 0.5°C.
Also from the details window I can set a 0.5°C increment/decrement: ifrom 19.6 I can set 19.1, 20.1, 20.6, ...
The precision of setting should reflect the precision of the thermostat, also becasue I can also set hot/cold tolerance to 0.1.

Problem-relevant configuration.yaml entries and (fill out even if it seems unimportant):

climate:
  - platform: generic_thermostat
    name: Piano Terra
    heater: switch.relay_1_pompa_pt
    target_sensor: sensor.temp_pt_temperature
    min_temp: 5
    max_temp: 30
    ac_mode: False
    target_temp: 19.6
    min_cycle_duration:
      minutes: 2
    cold_tolerance: 0.1
    hot_tolerance: 0.1
    initial_operation_mode: "auto"
    away_temp: 16
    precision: 0.1

**Comment by balloob** [comment] 2019-07-18 20:48
This is not a bug. The generic thermostat does not allow configuring `target_temperature_step`, which is the property that defines the step size for changing the target temperature.

**Comment by PhilRW** [comment] 2019-07-18 21:24
`temp_step` doesn't alter the UI behavior for me in the UI on 0.96 for MQTT climate. I can open a new issue if you want.

**Comment by balloob** [comment] 2019-07-18 21:54
Yeah,we should close this as this is not a bug. 

I tried to repro the temp step for https://github.com/home-assistant/home-assistant/issues/25252#issuecomment-512977005 but was unable to repro

**Closed by balloob** 2019-07-18 21:54 UTC

**Comment by Luc3as** [comment] 2020-01-20 10:23
> This is not a bug. The generic thermostat does not allow configuring `target_temperature_step`, which is the property that defines the step size for changing the target temperature.

I was hunting the same "bug" and found this thread. Is it possible to add   target_temp_step: funcionality to generic thermostat as well ?
