### ISSUE TITLE
History graph not up2date

### ISSUE THREAD

**Issue by sfarzie** [home-assistant/home-assistant-polymer#1050] opened 2018-03-30 13:18 UTC
Hi,
Here I am to re home an onld Issue (https://github.com/home-assistant/home-assistant-polymer/issues/1028).
After I restarted the Home assistant in order to update it to 0.65.6 everything works good but after 3-4 days some dysfunctions happened.

Here some screenshot:
![image](https://user-images.githubusercontent.com/31868317/38138866-3c595e98-342d-11e8-8126-2f5cc27051ed.png)
The relay is off and the UI correctly shows that it has been like that for 5 hours but the bar below shows it wrongly.

![image](https://user-images.githubusercontent.com/31868317/38138888-4d9035f6-342d-11e8-97de-538ed597aedf.png)
The current temperature is correct but the chart is got stuck

Here another example
![image](https://user-images.githubusercontent.com/31868317/38138943-9963f9f4-342d-11e8-9e7e-92e271186ee9.png)

**Comment by NovapaX** [comment] 2018-03-30 13:27
So the displayed state is correct (the right switch position, and the right temperature) But the history chart is not correct? Then this is not a issue with the frontend.
This has something to do with the recorder. Do you see any errors in the log? (the round `i` icon in the menu under developer tools? 
Also make sure your SD-card is not full (if you are running Hass.io) and check your configuration for the `history` and `recorder` component. (https://www.home-assistant.io/components/recorder/)

**Comment by corneyl** [comment] 2018-04-13 14:14
Does a restart of HA help? I had the same problem, but it was a problem with bad blocks in my database. In that case there should be an error in the log.

**Comment by sfarzie** [comment] 2018-04-14 09:15
I fixed it by deleting the DB file even thought there was available space in my sd card (32GB)...
The DB file was about 12GB

**Comment by fanaticDavid** [comment] 2018-04-14 09:25
If the issue is resolved, please close it.

**Closed** 2018-04-14 09:50 UTC
Labels: User feedback required
