### ISSUE TITLE
entity-button icon not reflecting state change in entity group

### ISSUE THREAD

**Issue by ptmoy2** [home-assistant/home-assistant-polymer#3312] opened 2019-06-28 02:00 UTC
**Home Assistant release with the issue:**

0.94.4

**Last working Home Assistant release (if known):**
Not known

**UI (States or Lovelace UI?):**

Lovelace

**Browser and Operating System:**

Firefox & Chrome

**Description of problem:**

The entity button icon (i.e., entity-button card in the UI) shows a different color for each state of the entity when the button controls a single device.  But if the entity button controls an entity that's a group, then icon remains the same color for all states.

For example: I have an entity button mapped to an MQTT switch with entity named switch.switch1.  Tapping the entity button turns the switch on and off, with the icon showing a different color for each of the two states.  However, if I define a group named group.two_switches consisting of switch.switch1 and switch.switch2 and assigning group.two_switches to the entity button, then toggling the entity button turns the two switches on and off, but the button icon doesn't change color.

If I used an entity card instead of the entity-button card, everything works as expected.

**Comment by mammuth** [comment] 2019-07-08 18:16
Might be related to #3060?

**Comment by iantrich** [comment] 2019-08-31 14:45
Duplicate of https://github.com/home-assistant/ui-schema/issues/178

**Closed by iantrich** 2019-08-31 14:45 UTC
