### ISSUE TITLE
UI anomaly on iPhone7

### ISSUE THREAD

**Issue by garyak** [home-assistant/home-assistant-polymer#4297] opened 2019-12-01 16:22 UTC
**Checklist:**

- [ x] I updated to the latest version available
- [x ] I cleared the cache of my browser

**Home Assistant release with the issue:**
102.3

**Last working Home Assistant release (if known):**
0.102.1

**UI (States or Lovelace UI?):**
Lovelace UI, Frontend version: 20191119.6 - latest

**Browser and Operating System:**
iOS Companion App 2.0 and iOS Safari 13.2.3 on iPhone 7

**Description of problem:**
iOS Companion App 2.0. iPhone 8 running same code does not exhibit this issue. iOS 13.2.3, HA 102.3. Can be corrected by switching panels, but returns. All panels effected. No errors reported in logs.

**Javascript errors shown in the web inspector (if applicable):**
N/A

**Additional information:**
![ui](https://user-images.githubusercontent.com/47036329/69916732-f4165c00-141b-11ea-9bfd-e11e1ece133d.jpeg)

**Comment by bramkragten** [comment] 2019-12-01 19:34
Try removing all custom cards first, to exclude that from being the cause.

**Comment by iantrich** [comment] 2020-01-17 03:50
closing with no reply

**Closed by iantrich** 2020-01-17 03:50 UTC
Labels: bug
