### ISSUE TITLE
Small annoyance login screen: Default focus first login field

### ISSUE THREAD

**Issue by frenck** [home-assistant/home-assistant-polymer#1705] opened 2018-09-25 19:19 UTC
**Home Assistant release with the issue:**

0.78.3

**Last working Home Assistant release (if known):**

n/a

**Browser and Operating System:**

Mac High Sierra, Chrome 69.

**Description of problem:**

In a login screen, I would expect the first field to be focussed automatically so I can start typing directly when the login screen pop-ups.

**Javascript errors shown in the web inspector (if applicable):**
```
n/a
```

**Additional information:**
![image](https://user-images.githubusercontent.com/195327/46037548-ba0b4500-c108-11e8-8d86-d7dd8d7468bd.png)

**Comment by cgarwood** [comment] 2018-09-26 19:03
Duplicate of #1641

**Closed by cgarwood** 2018-09-26 19:03 UTC
