### ISSUE TITLE
history not loading in Hassio 0.82.0

### ISSUE THREAD

**Issue by kajmaj** [home-assistant/home-assistant-polymer#2053] opened 2018-11-14 17:09 UTC
Home Assistant release with the issue:
0.82.0

Last working Home Assistant release (if known):
0.81.4

Operating environment (Hass.io/Docker/Windows/etc.):
Hass.io

Using default states UI

The history component just says "Loading State History ... " and never loads, after some time message "Loading State History ..." disappeared but no data displayed.
After this => Map, Records, Configurator, Hass.io, Configurator components are not possible to open - only the wheel it turning, Dev-info log is not displayed, other dev-components does not work as well => Hass.io reboots  on its own.
After that - everything works again, except history component.

I´ve reconfigured history.yaml and recorder.yaml as well, there are no includes nor excludes. 
Sensor templates seems to be working.

Any attempt to open history causes Home Assistant reboot.
There are no errors in log.

**Comment by iantrich** [comment] 2019-03-07 20:02
still an issue?

**Comment by iantrich** [comment] 2019-03-07 20:05
duplicate of #2045

**Closed by iantrich** 2019-03-07 20:05 UTC
Labels: Waiting for Reply
