### ISSUE TITLE
picture-* does not center after update

### ISSUE THREAD

**Issue by xNuno** [home-assistant/home-assistant-polymer#2330] opened 2018-12-15 19:09 UTC
**Home Assistant release with the issue:**

0.84.2

**Last working Home Assistant release (if known):**
None. This is new feature, edit object directly on browser.

**Browser and Operating System:**

Google Chrome - Windows 10 Latest

**Description of problem:**

When an object of the type: picture-* is created it gets content and the align center is lost.
As a workaround zoom out and zoom in on the browser puts everything on center again.
Is not possible to use the scrollbar as well since it works for the background/main content only!

**Javascript errors shown in the web inspector (if applicable):**
```

```

**Additional information:**
![image](https://user-images.githubusercontent.com/8095169/50046543-dfbb4100-009c-11e9-92d7-a45d2451a7ad.png)
![image](https://user-images.githubusercontent.com/8095169/50046546-eb0e6c80-009c-11e9-8a87-cd65e0b99de7.png)

**Comment by iantrich** [comment] 2018-12-15 19:11
Can you provide a gif showing this? I don’t get much from the screenshots

**Comment by xNuno** [comment] 2018-12-15 19:54
![issue](https://user-images.githubusercontent.com/8095169/50046903-2d3aac80-00a3-11e9-94da-0c54a85f78a2.gif)

**Comment by balloob** [comment] 2018-12-16 15:39
I think the issue about the dialog not being centered in the middle of the screen.

**Comment by zsarnett** [comment] 2018-12-16 19:56
This is an issue for the timing of our `resizeDialog` https://github.com/home-assistant/home-assistant-polymer/issues/2338 is a related issue

**Comment by iantrich** [comment] 2018-12-31 20:08
duplicate of https://github.com/home-assistant/home-assistant-polymer/issues/2338

**Closed by iantrich** 2018-12-31 20:08 UTC
Labels: Lovelace
