### ISSUE TITLE
Modals don't work in Vivaldi

### ISSUE THREAD

**Issue by theaquarium** [home-assistant/home-assistant-polymer#1624] opened 2018-09-01 21:26 UTC
**Home Assistant release with the issue:**

**Last working Home Assistant release (if known):**
0.76.2

**Browser and Operating System:**

Vivaldi 1.15.1174.64 on Windows and MacOS

**Description of problem:**

When an entity is clicked on the frontend (both old and lovelace), instead of opening a modal, nothing happens, and the following is written to the system log: `https://home.vashevko.com/states:1:1554 Uncaught`.

**Javascript errors shown in the web inspector (if applicable):**
```
Uncaught DOMException: Failed to construct 'CustomElement': The result must not have attributes
    at HTMLDocument.<anonymous> (<anonymous>:1:1554)
    at HTMLElement.<anonymous> (https://hassurl/frontend_es5/app-8dfe9b8d.js:2:801147)
    at j (https://hassurl/frontend_es5/compatibility-aeb5ab46.js:1:7551)
    at Generator._invoke (https://hassurl/frontend_es5/compatibility-aeb5ab46.js:1:7339)
    at Generator.t.(anonymous function) [as next] (https://hassurl/frontend_es5/compatibility-aeb5ab46.js:1:7730)
    at i (https://hassurl/frontend_es5/app-8dfe9b8d.js:2:801481)
    at https://hassurl/frontend_es5/app-8dfe9b8d.js:2:801620
    at new Promise (<anonymous>)
    at HTMLElement.r (https://hassurl/frontend_es5/app-8dfe9b8d.js:2:801418)
    at HTMLElement.ce.value (https://hassurl/frontend_es5/app-8dfe9b8d.js:2:801653)
```

**Additional information:**
This could have something to do with the websocket connection not working, because when the page is hard refreshed, the system log writes: `websocket connection is closing.`

**Comment by awarecan** [comment] 2018-09-01 22:52
Please check #1611, seems you are using frontend_es5, maybe try to force to use frontend_latest will resolve your issue.

**Comment by ludeeus** [comment] 2018-09-01 22:58
I tried it with `frontend_latest` that did not help for me

```yaml
frontend:
  javascript_version: latest
```

**Comment by theaquarium** [comment] 2018-09-02 13:58
yep, frontend_latest does not solve the issue.

**Comment by k-korn** [comment] 2018-09-28 15:56
Issue persists with Home Assistant 0.79 and Vivaldi 2.0.1309.29, with exactly the same error messages.

**Comment by theaquarium** [comment] 2018-09-28 19:14
https://stackoverflow.com/questions/43836886/failed-to-construct-customelement-error-when-javascript-file-is-placed-in-head seems to be the same issue.

**Comment by jack1142** [comment] 2018-10-04 12:52
It seems strange though as Vivaldi is using Chromium base as well. But anyway, I can't open modals in Vivaldi as well :/

**Comment by ktpx** [comment] 2018-10-17 13:46
I have the same problem. 

Btw, the homassistant demo page works.

**Comment by k-korn** [comment] 2018-10-17 18:48
> Btw, the homassistant demo page works.
Demo page (https://www.home-assistant.io/demo/ ) is on ancient version, 0.26  - so it's no wonder that it works.

**Comment by bartlech** [comment] 2018-10-17 20:59
Latest working release for me is 0.75.3 (not 0.76.2 as above) and I've just checked it again with docker containers, so probably there was some changes in 0.76 that caused this issue.

**Comment by ktpx** [comment] 2018-10-17 21:13
> > Btw, the homassistant demo page works.
> 
> Demo page (https://www.home-assistant.io/demo/ ) is on ancient version, 0.26 - so it's no wonder that it works.

LOL..damn, ancient stuff.

**Comment by tmooz** [comment] 2018-10-25 20:31
Same here: Home Assistant 0.80.3, Vivaldi 2.0.1309.42

**Comment by iantrich** [comment] 2018-10-26 20:32
Just to confirm, this is still an issue on 0.81 with Vivaldi 2.1.1337.36

**Comment by tocklime** [comment] 2018-11-21 13:45
Still an issue in 0.82.1, Vivaldi 2.1.1337.47. 

when I click something that should start a modal, I get 
```
app-79696026.js:7184 Uncaught DOMException: Failed to construct 'CustomElement': The result must not have attributes
    at HTMLElement._handleMoreInfo (https://myhassio.example.com/frontend_latest/app-79696026.js:7184:5076)
    at HTMLElement.addEventListener.e (https://myhassio.example.com/frontend_latest/app-79696026.js:7184:4814)
    at fireEvent (https://myhassio.example.com/frontend_latest/app-79696026.js:2088:13299)
    at HTMLElement.fire (https://myhassio.example.com/frontend_latest/app-79696026.js:139:816)
    at HTMLElement.badgeTap (https://myhassio.example.com/frontend_latest/app-79696026.js:4824:397)
    at HTMLElement.addEventListener.ev (https://myhassio.example.com/frontend_latest/app-79696026.js:4824:344)
_handleMoreInfo @ app-79696026.js:7184
addEventListener.e @ app-79696026.js:7184
fireEvent @ app-79696026.js:2088
fire @ app-79696026.js:139
badgeTap @ app-79696026.js:4824
addEventListener.ev @ app-79696026.js:4824
```

This is using frontend latest. frontend es5 also gives these errors, in addition to some 404 errors...

**Comment by CantConAnHonestJohn** [comment] 2018-12-21 18:54
Still an issue in 0.84.5, Vivaldi 2.2.1388.37.

**Comment by k-korn** [comment] 2018-12-23 07:18
Opened VB-47648 bug for Vivaldi, providing demo instance to test.
Let's see if they can fix it.

**Comment by iantrich** [comment] 2019-01-10 14:40
This is an upstream issue, I believe. Should probably file an issue with Vivaldi

**Comment by k-korn** [comment] 2019-01-10 16:06
Confirmed that this is a bug in Vivaldi:

From: Vivaldi Team <bugs@vivaldi.com>
Date: Thu, Jan 10, 2019 at 4:48 PM
Subject: [Jira] Re: [Jira] (VB-47648) Home Assistant modal windows do not
work
To: <...>

Hi,

Your bug was confirmed, but no progress yet.

**Comment by schmurtzm** [comment] 2019-01-22 22:23
Can we follow somewhere this Vivaldi's bug resolution ?

**Comment by bhaap** [comment] 2019-02-06 08:33
Im also interested in this. Is there a way to upvote the bug to the Vivaldi team so it gets more prio?

**Comment by k-korn** [comment] 2019-02-06 21:16
> Im also interested in this. Is there a way to upvote the bug to the Vivaldi team so it gets more prio?

Their bug tracker is not public, unfortunately.
But I suppose, mail to bugs@vivaldi.com with subject containing "[Jira] (VB-47648) Home Assistant modal windows do not work" will be routed to correct ticket.

**Comment by Cqoicebordel** [comment] 2019-02-16 22:51
I'm a volunteer helping Vivaldi a bit. I have access to the bug tracker, but can't influence much.

The bug was triaged (by volunteers) but that's all. No dev looked at it. And it has a very low priority. I'll try to bring a dev to look at it, but can't promise anything.

It's indeed a weird bug, as Vivaldi uses Chromium as its basis. Its reactions shouldn't be different.

**Comment by MarkMura** [comment] 2019-02-21 01:47
@Cqoicebordel I'm getting the same error on youtube - half of the page is broken, I cannot get to my profile. Do you think this would be a reason enough to raise the priority for the Vivaldi devs?

**Comment by Cqoicebordel** [comment] 2019-02-21 12:25
I'm not sure : if you are talking about a bug on YT where half of the UI isn't present, it's not the same bug. The one on YT is known, and being worked on, and in the mean time it seems it can be "fixed" by deleting the "VISITOR_INFO1_LIVE" cookie, or switching to Opera UA.

But for the bug here, it's more mysterious. I got a Q&A to look at it. He found Vivaldi's regression point, which wasn't helpful, because it was Chr54 intake, which had the CustomElement. So, in V, it was broken since the beginning. 

What would help would be a minimal test case. A webpage that can reproduce the issue with as few code as possible.
I would have done it myself if I could, but I have no idea what a CustomElement is. And I'm guessing people here are more knowledgeable. So if anyone here can reproduce the bug with as few code as possible, that would help the devs at V.

**Comment by Cqoicebordel** [comment] 2019-03-13 12:13
Just an FYI.
The root cause has been found, but it's a really complex issue. In the short term, the only solution would be to remove a feature of Vivaldi to have your website (and a couple others, but not a lot) works. The trade off is in discussion right now.
There will probably be a stable in the short term (~1-2 weeks). I doubt a fix will be present, but I'll keep you up to date if there is.

**Comment by Cqoicebordel** [comment] 2019-03-19 14:45
The latest snapshot should fix the issue (not yet on stable)
Spatial Navigation was what created the issue, so, for now, Vivaldi's implementation is at off per default. You can activate it, but it might (and probably will) break the page. The Chrome's implementation will work but is severely sub-par.
Anyway. It should work now.

**Comment by iantrich** [comment] 2019-03-19 14:48
The fix will allow for modals to work but will break the page as a whole?

**Comment by DanH42** [comment] 2019-03-19 15:14
@iantrich it sounds to me like Vivaldi switched their default spatial navigation implementation back to Chrome's, which gets the page working, but if a user changes their settings to use Vivaldi's improved implementation it will break the Home Assistant dashboard (and approximately zero other sites).

**Comment by Cqoicebordel** [comment] 2019-03-19 17:56
@DanH42 is right. Vivaldi's spatnav broke the pages (it broke also the new, in testing, interface of Youtube. So, yeah, a pretty big deal). The current "fix" is to deactivate Vivaldi's spatnav, but allow the users to either turn it back on, or turn on Chrome's implementation (which doesn't break anything but isn't really good).  
The big issue is that spatnav is an accessibility feature, so that fix isn't ideal. I think the long term solution would be to better integrate Chrome's implementation, and build upon it. But I might be a bit too verbose here, I don't think you really care about the future of spatnav in this thread ;)

**Comment by k-korn** [comment] 2019-03-19 19:15
Can confirm, Vivaldi snapshot 1488.4 restores Home Assistant modal windows:
https://vivaldi.com/blog/snapshots/closing-in-on-2-4-vivaldi-browser-snapshot-1488-4/

**Comment by k-korn** [comment] 2019-03-27 17:42
Vivaldi stable 2.4 has been released with a fix for this issue.
I suppose it can be closed here a well.

**Comment by iantrich** [comment] 2019-03-27 22:21
Just installed and it is indeed working. Thanks for keeping us updated on this @k-korn!

**Closed by iantrich** 2019-03-27 22:21 UTC
Labels: upstream issue
