### ISSUE TITLE
Lovelace Alarm Panel gives error "Invalid code given for disarmed"

### ISSUE THREAD

**Issue by donnib** [home-assistant/home-assistant-polymer#3178] opened 2019-05-09 06:39 UTC
**Home Assistant release with the issue:**
0.92.0

**UI (States or Lovelace UI?):**
```
title: Alarm
icon: mdi:shield-home
cards:
  - type: alarm-panel
    entity: alarm_control_panel.alarm
```

**Description of problem:**
I want to Disarm alarm so i type the code in (which i know is 100% correct) and click Disarm -> nothing happens.
Looking at the log i see : `Invalid code given for disarmed` in `components/manual/alarm_control_panel.py`, nothing else is states in the log. 
If i go to States and find the Alarm entity and type the code in there i can fine Disarm.
The alarm is of type manual.

**Additional information:**
I don't know if this issue is the same as https://github.com/home-assistant/home-assistant-polymer/issues/2602, it sounds like it but the error is not the same.

**Comment by iantrich** [comment] 2019-05-09 11:11
Do you actually type it on a keyboard? That doesn't work on the LL card. Already a ticket for that.

**Comment by donnib** [comment] 2019-05-09 11:26
@iantrich I use the physical keyboard from a PC. I haven't tried to use the included keypad. I will try if that makes a difference.

**Comment by Jizar07** [comment] 2019-07-06 00:39
no fix yet!!!!

**Comment by iantrich** [comment] 2019-09-02 04:08
Duplicate of https://github.com/home-assistant/home-assistant-polymer/issues/2602

**Closed by iantrich** 2019-09-02 04:08 UTC
